### ISSUE TITLE
Can't use promise libraries

### ISSUE THREAD

**Issue by bumpy1** [chaijs/chai-http#101]
According to the documentation I should be able to use the following code to use a custom promise library for older node environments:

```javascript
var chai = require('chai');
chai.use(require('chai-http'));

// Add promise support if this does not exist natively.
if (!global.Promise) {
  var q = require('q');
  chai.request.addPromises(q.Promise);
} 
```

But when I try it I get the following error: "Object has no method 'addPromises'".

**Comment by keithamus** [comment]
Hey @bumpy1 thanks for the issue.

`addPromise` was removed in `3.0.0` - it now defaults to the global Promise implementation. I shall update the docs to this effect.
