### ISSUE TITLE
disable following redirects

### ISSUE THREAD

**Issue by FreakinaBox** [chaijs/chai-http#112]
I am testing a redirect with
```
return this.client.get('/')
	.then(res => {
		expect(res).to.redirect;
	});
```
Everything works however when I inspect res I see that it followed all the redirects (3 in all).
This is timing out the test sometimes. We need an option to disable following redirects.

**Comment by keithamus** [comment]
Hey @FreakinaBox thanks for the issue.

There's a really easy way to disable redirects already: just add `.redirects(0)`. Of course this will make the Promise fail, so you need to counteract that. Something like this will work:

```js
return this.client.get('/')
    .redirects(0)
    .then(undefined, err => {
        expect(err.response).to.have.status(302).and.header('Location', '/some/path');
    });
```

Hopefully this helps @FreakinaBox. Let me know how it goes. For now I'm going to close this issue, but we can re-open it if you're still experiencing the same problem.

**Comment by FreakinaBox** [comment]
This seems like a hack instead of a planned way for things to work. I still think that we should be able to disable following redirects. With that said this did work for me
```
	it('should redirect', () => {
		this.Session.findOne.returns(Promise.resolve(null));
		return this.client.get('/')
			.redirects(0)
			.then(Promise.reject) //makes sure that everything gets passed to my error handler below.
			.catch(res => {
				expect(res).to.redirect;
			});
	});
```

**Comment by FreakinaBox** [comment]
correction, my second test case is failing.
```
		return this.client.get('/pingauth?code=123')
			.redirects(0)
			.then(Promise.reject) //makes sure that everything gets passed to my error handler below.
			.catch(res => {
				expect(res).to.have.cookie('token', 'testToken');
				expect(res).to.redirectTo('/');
			});
```
when I inspect the response i see that the cookie is set and the redirect is sent.
the first expect throws `TypeError: Cannot read property 'value' of undefined`
the second expect throws `AssertionError: redirect: expected header 'location' to have value / but got undefined`

I am guessing that this is do to an error res having a different structure than a success res.

**Comment by keithamus** [comment]
`res`, in your case is an `error` object, not the response you're looking for. What you want is `err.response`, e.g.:

```js
        return this.client.get('/pingauth?code=123')
            .redirects(0)
            .then(Promise.reject) //makes sure that everything gets passed to my error handler below.
            .catch(err => {
                expect(err.response).to.have.cookie('token', 'testToken');
                expect(err.response).to.redirectTo('/');
            });
```

Or you could get a bit funky and use destructuring...

```js
        return this.client.get('/pingauth?code=123')
            .redirects(0)
            .then(Promise.reject) //makes sure that everything gets passed to my error handler below.
            .catch(({ response }) => {
                expect(response).to.have.cookie('token', 'testToken');
                expect(response).to.redirectTo('/');
            });
```

**Comment by FreakinaBox** [comment]
didn't know that you could do that destructuring trick. thought I checked .response though. I will check again.

**Comment by FreakinaBox** [comment]
working, thanks

**Comment by MtDalPizzol** [comment]
I have a scenario where I need to test concurrent requests that can't follow the redirect.

So, I need to use Promise.all, but then, it will reject with the first error and I won't be able to test both responses, because I will only have the error for the first rejection.

It will be much better if I could get both responses within **.then**, not **.catch**

**Comment by austince** [comment]
@MtDalPizzol still in stage 2, but is [`Promise.allSettled`](https://github.com/tc39/proposal-promise-allSettled) what you're looking for? Either way, I'm not sure if this issue is the right place for this discussion - feel free to open another if you'd like to continue!

**Comment by Gaelan** [comment]
To any fellow googlers from the future, this now works:

```js
    expect(
      await request(app)
        .get("/")
        .redirects(0)
        .send()
    ).to.redirectTo("example.com");
```
