### ISSUE TITLE
can't install chai-http

### ISSUE THREAD

**Issue by nicowernli** [chaijs/chai-http#116]
Hi, I'm trying to install chai-http in an ubuntu 16.04 machine, but once I execute 
`npm install chai-http --save-dev`

I get the following error:
```
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "chai-http" "--save-dev"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! file /home/ubuntu/.npm/methods/1.1.2/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'T' at 1:1
npm ERR! TJ Holowaychuk","email":"tj@vision-media.ca","url":"http://tjholowaychuk.com"},
npm ERR! ^
npm ERR! File: /home/ubuntu/.npm/methods/1.1.2/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/brewerly/api/npm-debug.log
```

Do I need some special package in order to install chai-http?
Thanks in advanced

**Comment by meeber** [comment]
@nicowernli Looks like there's something wrong with the `methods` package (which is a dependency of chai-http) in your npm cache folder. However, the package hasn't been updated in 8 months, and I don't see anything relevant in the issue tracker, so I wonder if it's just a local caching issue on your system. Before digging any deeper, I'd say try cleaning the cache: `npm cache clean`

**Comment by nicowernli** [comment]
@meeber thank you very much for your help, cleaning the local cache was the solution, it is weird cause is a brand new vagrant machine and didn't install much with npm, but you solution worked fine.
