### ISSUE TITLE
Testing file download, res.files returns empty object

### ISSUE THREAD

**Issue by ajmas** [chaijs/chai-http#126]
Originally asked here: http://stackoverflow.com/questions/40517088/using-mocha-chai-to-ensure-rest-api-serves-up-a-file/

I am wanting to download the response file in a test, but the req.files value is an empty object. Displays as ``{}`` when displayed with console. The [superagent](https://visionmedia.github.io/superagent/) docs suggest that ``res.files`` should provide a file.

Note the endpoint works when testing with 'wget'.

The code I am using for my test

```
it('Should get a file', (done) => {
    chai.request(url)
        .get('/api/exercise/1?token=' + token)
        .end(function(err, res) {
            if (err) { done(err); }
            res.should.have.status(200);

            // Check the headers for type and size
            res.should.have.header('content-type');
            res.header['content-type'].should.be.equal('application/pdf');
            res.should.have.header('content-length');
            const size = fs.statSync(filepath).size.toString();
            res.header['content-length'].should.be.equal(size);

            // TODO get access to saved file and do tests on it
            //      tried 'res.files' but it returns {}                
        });
});
```

Is there something I am missing?

**Comment by meeber** [comment]
Not sure about the `file` property in this case since that's for multipart.

Dunno if there's a better way but looks like this is relevant: http://stackoverflow.com/questions/13573315/read-response-output-buffer-stream-with-supertest-superagent-on-node-js-server

Using the strategy in that article, I was able to test the md5 of some random pdf on the internets:

```js
"use strict";

const chai = require("chai");
const chaiHttp = require("chai-http");
const md5 = require("md5");

const expect = chai.expect;

chai.use(chaiHttp);

const binaryParser = function (res, cb) {
  res.setEncoding("binary");
  res.data = "";
  res.on("data", function (chunk) {
    res.data += chunk;
  });
  res.on("end", function () {
    cb(null, new Buffer(res.data, "binary"));
  });
};

it("merp", function (done) {
  chai
    .request("www.cbu.edu.zm/downloads/")
    .get("pdf-sample.pdf")
    .buffer()
    .parse(binaryParser)
    .end(function (err, res) {
      if (err) done(err);

      expect(res).to.have.status(200);
      expect(md5(res.body)).to.equal("fa7d7e650b2cec68f302b31ba28235d8");

      done();
    });
});
```

**Comment by ajmas** [comment]
Thanks. I have updated the question on stackoverflow, based on your solution.

**Comment by spoonscen** [comment]
meeber you saved my life.
