### ISSUE TITLE
Failing test throws an exception

### ISSUE THREAD

**Issue by itaied246** [chaijs/chai-http#134]
I'm using `chai-http` for testing my `express` server API.
When a test fails, I expect to see the cause and for the rest of the tests to continue, but instead I get an exception thrown, and the `done` function not even being called.

`  it('should create a user with password', done => {

    const mutation = `
    mutation createUserPassword {
      createUserPassword(email: "test@mail.com" name: "Full Name" password: "123456") {
        email
      }
    }`;

    const request = {
      query: mutation,
    };

    chai.request(app)
      .post('/graphql')
      .send(request)
      .end((err, res) => {
        expect(res.error).to.be.null;
        expect(res).to.have.status(200);
        expect(res.text.errors).to.not.exist;
        expect(res.text.data.createUserPassword.email).to.equal('test@mail.com');
        done();
      });
  });`

The test fails, and instead of the normal mocha information I get this:

`2016-12-22T11:15:03.319Z - error: uncaughtException: expected [Error: cannot POST /graphql (400)] to be null date=Thu Dec 22 2016 13:15:03 GMT+0200 (IST), pid=32342, uid=1000, gid=1000, cwd=/home/itai/dev/xchange, execPath=/home/itai/.nvm/versions/node/v6.5.0/bin/node, version=v6.5.0, argv=[/home/itai/.nvm/versions/node/v6.5.0/bin/node, /home/itai/dev/xchange/node_modules/mocha/bin/_mocha, test/**/*.test.js, --require, test/setup.js, --require, babel-register, --timeout, 15000], rss=236281856, heapTotal=194347008, heapUsed=106976480, loadavg=[0.88134765625, 0.69140625, 0.65771484375], uptime=656250, trace=[column=9, file=/home/itai/dev/xchange/test/mutation/createUserPassword.test.js, function=_get__.request.post.send.end, line=32, method=request.post.send.end, native=false, column=3, file=/home/itai/dev/xchange/node_modules/superagent/lib/node/index.js, function=Test.Request.callback, line=631, method=Request.callback, native=false, column=18, file=/home/itai/dev/xchange/node_modules/superagent/lib/node/index.js, function=null, line=795, method=null, native=false, column=7, file=/home/itai/dev/xchange/node_modules/superagent/lib/node/parsers/json.js, function=, line=16, method=null, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=185, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=974, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[AssertionError: expected [Error: cannot POST /graphql (400)] to be null,     at _get__.request.post.send.end (/home/itai/dev/xchange/test/mutation/createUserPassword.test.js:32:9),     at Test.Request.callback (/home/itai/dev/xchange/node_modules/superagent/lib/node/index.js:631:3),     at /home/itai/dev/xchange/node_modules/superagent/lib/node/index.js:795:18,     at IncomingMessage.<anonymous> (/home/itai/dev/xchange/node_modules/superagent/lib/node/parsers/json.js:16:7),     at emitNone (events.js:91:20),     at IncomingMessage.emit (events.js:185:7),     at endReadableNT (_stream_readable.js:974:12),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]`

What am I doing wrong and why is this happening?

**Comment by meeber** [comment]
> When a test fails, I expect ... for the rest of the tests to continue

When a test fails, an error is thrown, and the rest of the statements inside of the function will never execute. For example:

```js
it("test", function () {                                                         
  expect(true).to.be.false; // Throws an AssertionError
  expect(2).to.equal(2); // This will never run                                 
});
```

If you want each test to run even if the one before it fails, then each test needs to be inside of its own `it` block.

> When a test fails, I expect to see the cause

The problem is that your failing test occurs inside of a Promise. The Promise swallows the AssertionError, and thus it never gets reported to Mocha. In your example, you have two options for reporting the AssertionError to Mocha.

Option 1:

```js
it('should create a user with password', done => {
  <...stuff...>

  chai.request(app)
    .post('/graphql')
    .send(request)
    .end((err, res) => {
      expect(res.error).to.be.null;
      expect(res).to.have.status(200);
      expect(res.text.errors).to.not.exist;
      expect(res.text.data.createUserPassword.email).to.equal('test@mail.com');
      done();
    })
    .catch(done);  // Provide the `done` function as the error handler for this Promise chain
}
```

Option 2:

```js
it('should create a user with password', () => {  // Remove `done` so Mocha no longer expects it
  <...stuff...>

  return chai.request(app)    // Return the Promise; Mocha will know what to do with it
    .post('/graphql')
    .send(request)
    .end((err, res) => {
      expect(res.error).to.be.null;
      expect(res).to.have.status(200);
      expect(res.text.errors).to.not.exist;
      expect(res.text.data.createUserPassword.email).to.equal('test@mail.com');
      // Removed `done` call; the returned Promise will mark end of async test instead
    });
    // No catch statement is needed; if a test fails, the Promise will be rejected, and Mocha will report it
}
```

**Comment by itaied246** [comment]
For the first question, I know that if some assertion fails then the following assertions won't execute.
But I in the problem I have described, probably not clear enough, the following `it` blocks didn't execute.

I really liked your second option with returning the promise to mocha. I adopted it and now my tests run as I expected.
Thanks!
