### ISSUE TITLE
Strip localhost from redirects

### ISSUE THREAD

**Issue by erbridge** [chaijs/chai-http#140]
It would be very helpful to be able to test a redirect using something like this:

```js
agent.get('/').then(res => {
    expect(res).to.redirectTo('/login');
})
```

Without needing to construct `http://127.0.0.1:36851/login`.

**Comment by keithamus** [comment]
@erbridge thanks for the issue. You probably want to instead check that `/` sets a 301/302 with a `Location` header, instead:

```
agent.get('/').redirects(0).catch((err) => err.res).then(res => {
    expect(res).to.have.status(302);
    expect(res).to.have.header('location', '/login');
})
```

Let me know how you get on with this. I'll close this for now but we can keep the discussion going 😄

**Comment by erbridge** [comment]
That seems to work, thanks. Though it's `err.response`, not `err.res`.
