### ISSUE TITLE
response body empty for binary content-type

### ISSUE THREAD

**Issue by reesew** [chaijs/chai-http#141]
I have a contract test where the response type is a binary file. In my test, the res.body property appears to be unpopulated, despite a body actually being returned.

```
chai.request(app)
  .post('/compose')
  .set('Content-Type', "application/json")
  .set('Accept', "application/octet-stream")
  .send(data)
  .end(function onEnd(e, res) {
    expect(res).to.have.status(200);
    var binary = res.body;
```

In the above example, I expect res.body to contain the binary response body, but it looks like an empty object. If this is expected behavior, is there an option or parameter to set in order to inspect the response body?

**Comment by meeber** [comment]
Is #126 applicable to your issue?

**Comment by reesew** [comment]
@meeber yes, adding the `buffer()` and `parse()` lines to the chain caused `res.body` to be populated. Where are those functions even documented?

**Comment by meeber** [comment]
chai-http is built on top of [superagent](http://visionmedia.github.io/superagent/), so anything in their docs should apply. Also just saw this: https://github.com/abelcha/superagent-binary-parser which seems to be taking a similar approach to the issue.
