### ISSUE TITLE
Async loaded routes

### ISSUE THREAD

**Issue by Falci** [chaijs/chai-http#143]
How to test an app that has routes created async?

 ```javascript
const express = require('express');
const app = express();

setTimeout(() => {
  app.get('/hey', (req, res) => {
    res.status(204).end();
  });

  console.log('route defined');
}, 5000);

app.listen(3333, function () {
  console.log('listening');
});

export = app;
```

**Comment by edrpls** [comment]
I'm having this same question, I found that you can listen to specific events with superagent, but not so sure if it would work with chai-http too.

https://mrvautin.com/ensure-express-app-started-before-tests/

**Comment by edrpls** [comment]
Update: Can confirm that emitting an event works, I had to modify the timeout too since my setup took longer than mocha expected:

``` javascript
before(function (done) {
    this.timeout(5000);
    app.on('appStarted', () =>
        user.login().then(() => done()));
});
```

**Comment by Falci** [comment]
I believe the `app.listen` is called before app be ready, but I got your point. I guess this solution may work fine.

I'm using pleerock/routing-controllers to load the routes. I'll create a PR there to emit the event.

Thank you for your help 👍

**Comment by Falci** [comment]
My real problem was not the async call.
More details in the related ticket.
