### ISSUE TITLE
Testing a property on the res.locals object. 

### ISSUE THREAD

**Issue by Mozar10** [chaijs/chai-http#146]
Consider this: 

`router.get('/', function (req, res) {

        res.locals.authenticated = false;
        res.render('index');

});`

Testing this will result in a TypeError

`it('should respond with contents of the homepage', function (done) {

    chai.request(server).get('/').end(function (err, res) {
        expect(err).to.be.null;
        expect(res.status).to.equal(200);
        expect(res.locals.authenticated).to.be.false; //This will result in TypeError
        expect(res).to.be.html;
        done();
    });
});`

I know that as explained in the express docs (http://expressjs.com/en/api.html#res.locals) the res.locals is only available to the views being rendered but I'm wondering, is there a way to test a property on the res.locals object some other way ?

**Comment by austince** [comment]
Hey @mozar10, thanks for the issue! `chai-http` is more for full end-to-end HTTP testing, which would not have access to the Express-specific Request and Response objects. I think you might be able to do these tests lower down in your stack [as people suggest here](https://stackoverflow.com/questions/34516951/express-middleware-testing-mocha-chai) or with [node-http-mocks.](https://github.com/howardabrams/node-mocks-http)
