### ISSUE TITLE
HTTP 307 and 308 status codes are not treated as redirects

### ISSUE THREAD

**Issue by BigstickCarpet** [chaijs/chai-http#147]
Not sure if this is by design or not, but the `.redirect` and `.redirectTo` assertions currently [only test for 301, 302, and 303 status codes](https://github.com/chaijs/chai-http/blob/2ae97dd4b36df4e7b9f2089eaf7a491d65b96401/lib/http.js#L247).  Shouldn't this list also include HTTP 307 (Temporary redirect) and HTTP 308 (Permanent redirect)?

**Comment by vieiralucas** [comment]
Hello @BigstickCarpet, thanks for your issue.

It seems reasonable to me that `chait-http` could support 307 and 308 on the `.redirect` and `.redirectTo` assertions.

It looks like you already now where to fix that, would you like to make a PR?

**Comment by BigstickCarpet** [comment]
Ok, I'll submit a PR when I get a free moment.  May not be for a few weeks though, because I'm about to leave for vacation

**Comment by keithamus** [comment]
but the commit is right there! 😨

**Comment by BigstickCarpet** [comment]
hahaha... gotta fork the repo, checkout, branch, commit, test, open a PR...  Ain't nobody got time for that!  😸

**Comment by tonymet** [comment]
Added PR #154 with @BigstickCarpet 's change. Thanks all this was a blocker for us too :D

**Comment by vieiralucas** [comment]
Closed by #154
