### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by joetidee** [chaijs/chai-http#150]
I have this test file:

import React from 'react';
import { mount, shallow } from 'enzyme';
import chai from 'chai';
var expect = chai.expect;
var assert = chai.assert;
import chaiEnzyme from 'chai-enzyme';
import chaiHttp from 'chai-http';
chai.use(chaiEnzyme());
//chai.use(chaiHttp);

When I uncomment the line `chai.use(chaiHttp);` I get the following error:

> /tidee/au/node_modules/chai-http/lib/http.js:166
>         this._obj.headers || this._obj.getHeader
>                  ^
> TypeError: Cannot read property 'headers' of undefined
>     at Assertion.<anonymous> (/tidee/au/node_modules/chai-http/lib/http.js:166:18)
>     at Assertion.addProperty (/tidee/au/node_modules/chai/lib/chai/utils/addProperty.js:43:29)
>     at Object.<anonymous> (/tidee/au/node_modules/chai-http/lib/http.js:215:39)
>     at Object.addProperty (/tidee/au/node_modules/chai/lib/chai/utils/addProperty.js:43:29)
>     at ChaiWrapper.addAssertion (/tidee/au/node_modules/chai-enzyme/build/ChaiWrapper.js:46:40)
>     at /tidee/au/node_modules/chai-enzyme/build/index.js:111:17
>     at Object.exports.use (/tidee/au/node_modules/chai/lib/chai.js:40:5)
>     at Object.<anonymous> (/tidee/au/.tmp/mocha-webpack/test_index.js:559:16)
>     at __webpack_require__ (/tidee/au/.tmp/mocha-webpack/test_index.js:20:30)
>     at webpackContext (/tidee/au/.tmp/mocha-webpack/test_index.js:243:9)
>     at Array.forEach (native)
>     at Object.<anonymous> (/tidee/au/.tmp/mocha-webpack/test_index.js:1039:21)
>     at __webpack_require__ (/tidee/au/.tmp/mocha-webpack/test_index.js:20:30)
>     at /tidee/au/.tmp/mocha-webpack/test_index.js:66:18
>     at Object.<anonymous> (/tidee/au/.tmp/mocha-webpack/test_index.js:1:10)
>     at Module._compile (module.js:571:32)
>     at loader (/tidee/au/node_modules/babel-register/lib/node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/tidee/au/node_modules/babel-register/lib/node.js:154:7)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at /tidee/au/node_modules/mocha/lib/mocha.js:222:27
>     at Array.forEach (native)
>     at Mocha.loadFiles (/tidee/au/node_modules/mocha/lib/mocha.js:219:14)
>     at Mocha.run (/tidee/au/node_modules/mocha/lib/mocha.js:487:10)
>     at /tidee/au/node_modules/mocha-webpack/lib/cli/runner.js:59:11
>     at Compiler.<anonymous> (/tidee/au/node_modules/mocha-webpack/lib/webpack/createCompiler.js:78:7)
>     at Compiler.applyPlugins (/tidee/au/node_modules/tapable/lib/Tapable.js:61:14)
>     at /tidee/au/node_modules/webpack/lib/Compiler.js:255:13
>     at Compiler.emitRecords (/tidee/au/node_modules/webpack/lib/Compiler.js:351:37)
>     at /tidee/au/node_modules/webpack/lib/Compiler.js:249:12
>     at /tidee/au/node_modules/webpack/lib/Compiler.js:344:11
>     at next (/tidee/au/node_modules/tapable/lib/Tapable.js:154:11)
>     at Compiler.compiler.plugin (/tidee/au/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>     at Compiler.applyPluginsAsyncSeries1 (/tidee/au/node_modules/tapable/lib/Tapable.js:158:13)
>     at Compiler.afterEmit (/tidee/au/node_modules/webpack/lib/Compiler.js:341:8)
>     at Compiler.<anonymous> (/tidee/au/node_modules/webpack/lib/Compiler.js:336:14)
>     at /tidee/au/node_modules/async/dist/async.js:356:16
>     at iteratorCallback (/tidee/au/node_modules/async/dist/async.js:936:13)
>     at /tidee/au/node_modules/async/dist/async.js:840:16
>     at /tidee/au/node_modules/graceful-fs/graceful-fs.js:43:10
>     at FSReqWrap.oncomplete (fs.js:111:15)
>

**Comment by vieiralucas** [comment]
Hello @joetidee I tried to reproduce your issue with those following steps:

1. `npm install --save-dev babel-core babel-preset-es2015 babel-preset-stage-0`
2. `npm install --save-dev mocha chai chai-http enzyme chai-enzyme react-addons-test-utils`
3. `npm install --save react react-dom`

Then I wrote your code in a `test.spec.js` file

```js
import React from 'react';
import { mount, shallow } from 'enzyme';
import chai from 'chai';
var expect = chai.expect;
var assert = chai.assert;
import chaiEnzyme from 'chai-enzyme';
import chaiHttp from 'chai-http';
chai.use(chaiEnzyme());
chai.use(chaiHttp);
```

I tried to just run it with `babel-node`
- `./node_modules/.bin/babel-node test.spec.js`
The code executed without errors

Also I tried to executed with mocha
- `./node_modules/.bin/mocha --compilers js:babel-core/register test.spec.js`
This executed without errors too

I see you are running through webpack
Can you provide more detail on how to reproduce this issue? Would be awesome if you could provide a public repo that reproduces it.

Thank you and sorry for not being able to help yet.

**Comment by joetidee** [comment]
Thanks for your prompt reply. So, I am running an express server and also running tests using mocha-webpack. The entry point to my tests is a file that requires each test file. If I have two test files that use chai-http, then I get the aforementioned errors thrown, however, if I only include one test file I do not get any errors (!)

Have sent a link for the private repo to your email address.

**Comment by vieiralucas** [comment]
@joetidee I could not really find the root cause of the problem.
But I think I managed to work around it.

You could add all your `chai.use` calls to the `test_index.js`
```js
import chai from 'chai';
import chaiEnzyme from 'chai-enzyme';
import chaiHttp from 'chai-http';
chai.use(chaiEnzyme());
chai.use(chaiHttp);

var testsContext = require.context(".", true, /_test$/);
testsContext.keys().forEach(testsContext);
```

Doing it this way you will not need to call `chai.use(chaiHttp)` two times

**Comment by joetidee** [comment]
This doesn't seem to work as I need the folowing in the individual test files and the error `chai is not defined` is being thrown:

```
var expect = chai.expect;
var assert = chai.assert;
```

**Comment by vieiralucas** [comment]
You can still do
```js
import chai from 'chai';
var expect = chai.expect;
var assert = chai.assert;
```
You just don't need to call `chai.use` anymore.

You could also do
```js
import { expect, assert } from 'chai';
```

**Comment by joetidee** [comment]
ok, this works :) Many thanks.

Is the above error somethign that you will look to address?

**Comment by vieiralucas** [comment]
@joetidee I'm not sure this is really a problem with `chai-http` it might be something wrong with `mocha-webpack` or something else you were doing.

So I'm gonna **close** this for now since we manage to solve your problem.

Feel free to open another issue if you manage to provide a more focused way of reproducing this.

Thanks

**Comment by joetidee** [comment]
Ok, so just out of interst, what is this saying:

/tidee/au/node_modules/chai-http/lib/http.js:166
this._obj.headers || this._obj.getHeader
^
TypeError: Cannot read property 'headers' of undefined
at Assertion. (/tidee/au/node_modules/chai-http/lib/http.js:166:18)

**Comment by perrin4869** [comment]
In case anyone else ends up here, I have a (less than ideal) workaround:

```javascript
const chai = require('chai');

const propertyToMethod = (name) => (chai, utils) => {
  const { Assertion } = chai;
  const { get } = Object.getOwnPropertyDescriptor(Assertion.prototype, name);
  delete Assertion.prototype[name];
  utils.addMethod(Assertion.prototype, name, get);
};

chai.use(require('chai-http'));

chai.use(propertyToMethod('html'));
chai.use(propertyToMethod('text'));

chai.use(require('chai-enzyme')());
```
