### ISSUE TITLE
Any plans for a new release soon?

### ISSUE THREAD

**Issue by richardpringle** [chaijs/chai-http#151]
Are there any plans for new release soon, be it major, minor, or even a patch version?

**Comment by vieiralucas** [comment]
@keithamus can you help here?

**Comment by keithamus** [comment]
Plan to spend some time soon getting this inline with other packages like deep-eql, so releasing on semantic-release, following standardised way of doing things for chai. Right now all I have is "soon" 😄

**Comment by rageshvr** [comment]
@keithamus I was about to message you in twitter to ask you this. How long the wait 😞 , is it soon or so soon?  There are a few merges that we are waiting for 😄

**Comment by barraponto** [comment]
hey @keithamus if you want to hold a weekend task-force to work on chai-http and related projects, let us know :)

**Comment by bjornstar** [comment]
It would be really helpful if someone could make a release on npm. If everyone is too busy to do it, would you consider giving someone else the ability to do it? I'd be happy to help on that front.

**Comment by barraponto** [comment]
@bjornstar you can publish to your own namespace, and we can start testing it.

**Comment by keithamus** [comment]
For now you are welcome to run `npm install github:chaijs/chai-http#master`. A release will happen soon.

**Comment by shanehughes3** [comment]
I hate to be annoying, but... any update here? We're closing in on a year for this issue. There are a number of features and changes in master that are ready to be published, and I'd really prefer not to leave a github link in my package.json where an npm package would be possible.
