### ISSUE TITLE
[feature] async/await style of examples

### ISSUE THREAD

**Issue by imkimchi** [chaijs/chai-http#156]
I was immigrating my codes to ES6 with async/await and I just started to use testing framework with chai. As I see some examples on the page, I found it that examples are written in old syntax.
It's been about 2 month since async/await feature came out to the Node world. I'd suggest to change example codes to async/await style rather than promise style code, and It seems like core codes are written in old syntaxes as well, It would be awesome if somebody immigrates codes to ES6 style.

**Comment by vieiralucas** [comment]
Hello @imkimchi, thanks for your issue.

IMO we could add examples using the new `async/await` features of Node 7.

I don't think we should remove the old examples:

- `chai-http` still supports old versions of node that don't have support for `async/await`
- Users that know how to use `async/await` can easily translate from `Promises`, but the other way around may not be true.

**Comment by darlanmendonca** [comment]
I'm looking for better way to write my specs using async/await. Is very useful write

```js
it('should return an array', async () => {
  const res = await get('/users')

  expect(res).to.be.json
  expect(res).to.have.status(200)
  expect(res.body).to.be.an('array')
})
```

instead write

```js
it('should return an array', (done) => {
  get('/users')
  .end((err, res) => {
    expect(res).to.be.json
    expect(res).to.have.status(200)
    expect(res.body).to.be.an('array')
    done()
  })
})
```

But the async/await cannot be write to promises that are reject, for example, if my API response with a 400 (Bad Request), this reject promise instead resolve it

And my question is, dont be better always resolve the promise, once the request was responded?

**Comment by darlanmendonca** [comment]
What I want is clen up my code, inclusively to bad requests, like example below

```js
it('should return an array', async () => {
  const res = await post('/users')

  expect(res).to.be.json
  expect(res).to.have.status(400)
  expect(res.body).to.be.an('object')
  expect(res.body).to.have.property('message', 'params email and password is required')
})
``

**Comment by keithamus** [comment]
@darlanmendonca this will be fixed in the next version of chai-http. See #130 and #75

**Comment by darlanmendonca** [comment]
@keithamus nice!! awaiting for next release :D

**Comment by deefour** [comment]
@keithamus any plan to tag a new release?

**Comment by ashton** [comment]
+1

I've set my dependency to chai-http:master but because of that, I added GIT dependency to my build process, I've had to change my base image from node:alpine to node:wheezy, because alpine and slim tags doesn't include GIT, and wheezy makes my project image grows from, 45mb to 621mb, if you could priorize this in the next release would be great!

**Comment by joaomlneto** [comment]
Just putting it here in case it's useful to someone -- current code on `master` works fine, except for this tiny bit:
https://github.com/mochajs/mocha/issues/2407

The following code will fail with `Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.`:
```
it 'should work', (done) ->
  res = await chai.request(server).get(url)
  done()
```
Removing the `done` argument solves it.

**Comment by deefour** [comment]
@joaomlneto Here's what mine look like.

```javascript
it('requires authentication', async () => {
  let res = await chai
    .request(app)
    .post('/billing/card');

  expect(res.status).to.eql(401);
});
```

And yeah, `master` works, but pointing at it via `package.json` seems to cause it to get pruned periodically from unrelated npm commands. This is why I was hoping to see a new release tagged.

```
"chai-http": "git+https://github.com/chaijs/chai-http.git",
```

**Comment by gfviegas** [comment]
@joaomlneto but does the test passes even though there's an assertion error?

I'm doing the same but it looks like the suite passes since async function automatically return promises and won't wait for my expect to run

**Comment by deefour** [comment]
@gfviegas I'm unclear; are you having an issue or not? If so what's your test look like?

**Comment by gfviegas** [comment]
@joaomlneto @deefour 

Nevermind.. I just figured it out that I had a try/catch block and forgot to throw the catched error so mocha could catch it.

**Comment by foodaka** [comment]
@joaomlneto im getting a timeout error using this syntax. any ideas?;

   Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


```
  it('should POST /orders', async (done) => {
    const passingOrder = {
      catItemId: 0,
      countryId: 1,
      orderName: "Order-493623",
      serviceLevelId: 2
    }
    
    try {
      const res = await chai.request(app)
      .post('/orders')
      .set('authorization', 'Bearer ' + authToken)
      .send([passingOrder])

        res.should.have.status(200);
        res.body[0].should.be.a('object');
        res.body[0].should.have.property('status');
    } catch(err) {
      throw err;
    }
  });

```

**Comment by zetos** [comment]
@foodaka remove the `done` argument and it should work fine. The `done` is just for callbacks and you are using promises.

**Comment by foodaka** [comment]
Thanks for the replies @joaomlneto and @zetos , it was a bug on my side. I also listened to @zetos and removed the done from the function params.

**Comment by keithamus** [comment]
Thanks @joaomlneto 👍 

If anyone wants to continue the discussion feel free, or also feel free to open a new issue if you think this hasn't been fully resolved!
