### ISSUE TITLE
Doesn't send body in PUT request

### ISSUE THREAD

**Issue by wzup** [chaijs/chai-http#165]
No `body` in `req.body`. Neither of both sets `req.body`: `field` and `send`.
Why? What's wrong?

Set up:
```
const util = require('util');
const assert = require('assert');
const chaiHttp = require('chai-http');
const chai = require('chai');
const expect = chai.expect;
chai.use(chaiHttp);

chai.request('http://foo.com:3030')
    .put('/api/endpoind')
    .field('foo', 'http://foo.com:3030')
    .send({'bar': 'http://bar.com:3030'})
    .query({
        a: 'aaaaa',
        b: 'bbbbb',
        c: 'ccccc'
    })
    .end(function(err, res) {
        if (err) {
            console.error(err);
            done();
        }
        done();
    });
```

And `req.body` is an empty object
```
(req, res, next) => {
    console.log(req.body) // ==> {}
}
```

**Comment by meeber** [comment]
@wzup Check out https://github.com/chaijs/chai-http/pull/97#issuecomment-222397088 to see if it's related to your issue. I've never used this plugin personally and don't have time to dig in right now so it's hard for me to say for sure.

**Comment by wzup** [comment]
Both methods do not work, `.field`, `.send`.

I also found that the plugin doesn't set headers.

I set:
```
.set('content-type', 'application/json')
```

I receive:
```
  'user-agent': 'node-superagent/2.3.0',
  'content-type': 'multipart/form-data; boundary=--------------------------716330614312092759651257',
```

And on top of that, I get this when I run tests. Any test, every time:

> Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

This plugin creates more issues than it solves.

**Comment by meeber** [comment]
chai-http is built on top of the [superagent](https://github.com/visionmedia/superagent) library. I believe the `.field` method is telling superagent that a multipart request is being performed; that's why your  header isn't being respected. I have no doubt that the documentation is wrong/outdated; the creator of this plugin hasn't been active in 4+ years. This plugin (and Chai in general) is 100% community supported, and survives only on kind people making contributions when they find problems.

**Comment by wzup** [comment]
Here are approaches that work. The `req.body` is not received as an empty object.

1. https://github.com/chaijs/chai-http/pull/97#issuecomment-304751016

1. This is as a form data.
```
.put('/path/endpoint')
.type('form')
.send({foo: 'bar'})
.end(function(err, res) {}

// headers received, set by the plugin apparently
  'accept-encoding': 'gzip, deflate',
  'user-agent': 'node-superagent/2.3.0',
  'content-type': 'application/x-www-form-urlencoded',
  'content-length': '127',
```
Many thanks to @barraponto. There is his answer here https://github.com/chaijs/chai-http/pull/97#issuecomment-304751016.

2. This is as `application/json`:
```
.put('/path/endpoint')
.set('content-type', 'application/json')
.send({foo: 'bar'})

// headers received, set by the plugin apparently
  'accept-encoding': 'gzip, deflate',
  'user-agent': 'node-superagent/2.3.0',
  'content-type': 'application/json',
  'content-length': '105',
```

In both cases `.send()` is used. `.field()` doesn't work at all.

To authors.
How is it possible that there is nothing about `.type('form')` in your docs? Do you think we should guess how your puzzle works?

**Comment by wzup** [comment]
More [here](http://visionmedia.github.io/superagent/#-post-put-requests)
> By default sending strings will set the Content-Type to application/x-www-form-urlencoded,

**Comment by curtis-n** [comment]
Just as a side note, I found that the reason my body parameters was empty was because I had called the appropriate middleware functions in the wrong order in the node.js express server.

For example, this left the body empty
```javascript
var express = require('express');
var app = express();
var routesApi = require('./routes/routes');
var bodyParser = require('body-parser');

app.use('/api', routesApi);
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```

And this filled the body parameters the correct way
```javascript
var express = require('express');
var app = express();
var routesApi = require('./routes/routes');
var bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use('/api', routesApi);
```

**Comment by barraponto** [comment]
@curtis-n I'd usually recommend against setting both json and urlencoded body parsers globally. The performance hit is minimal for running both by default, but I'd rather have my route defined as `app.post('/api/comments', jsonParser, (req, res) => {...})` just to let the parser explicit. I see no problems with router-wise middlewares though.

**Comment by catalinberta** [comment]
@wzup 
You need to put a body parser before setting up the route with `use`

`
const bodyParser = require('body-parser');
const express = require('express');
const route = require('routes/myRoute');

const app = express();
app.use(bodyParser.json());
app.use('/path', route);

chai.request(app)
				.post('/')
				.send({ login: 'test', password: 'test' })
				.end((err, res) => {
					expect(res).to.have.status(200);
					done();
				});
`

See SO answer: https://stackoverflow.com/questions/39470566/request-body-undefined-in-supertest

**Comment by rider-cantuaria** [comment]
> Just as a side note, I found that the reason my body parameters was empty was because I had called the appropriate middleware functions in the wrong order in the node.js express server.
> 
> For example, this left the body empty
> 
> ```js
> var express = require('express');
> var app = express();
> var routesApi = require('./routes/routes');
> var bodyParser = require('body-parser');
> 
> app.use('/api', routesApi);
> app.use(bodyParser.urlencoded({ extended: true }));
> app.use(bodyParser.json());
> ```
> 
> And this filled the body parameters the correct way
> 
> ```js
> var express = require('express');
> var app = express();
> var routesApi = require('./routes/routes');
> var bodyParser = require('body-parser');
> 
> app.use(bodyParser.urlencoded({ extended: true }));
> app.use(bodyParser.json());
> app.use('/api', routesApi);
> ```

This work to me...
