### ISSUE TITLE
Readme can be misleading

### ISSUE THREAD

**Issue by cornelius-k** [chaijs/chai-http#172]
The readme makes use of expect, but never requires chai.expect.
I recommend adding
`var expect = chai.expect;`

**Comment by vieiralucas** [comment]
Hello, @cornelius-k thanks for the issue

Are you interested in submitting a PR addressing this?

**Comment by cornelius-k** [comment]
Sure! https://github.com/chaijs/chai-http/pull/173

Let me know if anything should be changed to follow branch name / PR name conventions.

**Comment by austince** [comment]
Closed with https://github.com/chaijs/chai-http/pull/173
