### ISSUE TITLE
Include does not work with object despite the specs

### ISSUE THREAD

**Issue by herrjemand** [chaijs/chai-http#175]
So I am testing my API, that returns something like this:

```
{
    "authToken": "osujOkJpGLyhTVc9DBqs37U24PaBpz5CBC8k5Dr2"
}
```

When I run on response `expect(response.body).should.deep.include('authToken');` I get

> Uncaught AssertionError: object tested must be an array, a map, an **object**, a set, a string, or a weakset, but **object** given

**Comment by meeber** [comment]
This should be fixed in Chai v4.1.1 and later per https://github.com/chaijs/chai/pull/1012
