### ISSUE TITLE
Configure rejectUnauthorized per-request option

### ISSUE THREAD

**Issue by rusekr** [chaijs/chai-http#180]
Hello!
Need standart nodejs functionality for internal testing / production certificate update issues temp fixes.

Tried to convince author of superagent lib you are using here: https://github.com/visionmedia/superagent/pull/1207#issuecomment-336940481
 but with no luck.

Any suggestions? 
And thanks!

**Comment by keithamus** [comment]
Hey @rusekr thanks for the issue.

We're beholden to the SuperAgent API. If they're not interested in pursuing it (for seemingly good reasons) I'm not sure we can. 

I'll close this for now. If you can provide a very strong use case for this with some example code I'd happily re-open though 😄

**Comment by rusekr** [comment]
Hello!
Argument 1: What can be stronger than nodejs itself including it? https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

Argument 2: it is TEST framework or not? it is for testing, testing not always happens with green certs (and problems/time of installing it) or on own systems where i can set cert.

Argument 3: We have web-system integrated with big company. we are using api they provide for billing related stuff in close environment. recently that api got cert expired. Our api uses rejectUnauthorized: true for now (it's close environment anyway) but our 81 tests for checking real responses from methods of this api across the country nodes do not work! Now we got "cert expired". And it can't be easily avoided because of lack of configurability. And author of superagent thinks he can tell another people what is good and what is bad, he konws it better than nodejs developers  rejecting pull requests that he can simply merge.

With only that one simple issue unresolved i got huge argument against using superagent lib and testing frameworks using it, and advertize not to using it to not to fail as we failed unexpectedly in real life big system. Not ideal land with 100% HA and always green certs or own servers as author of superagent thinks.

Now i need to migrate to jasmine or something reworking all tests because expired cert problem seems to be here another several weeks.

**Comment by rusekr** [comment]
Argument 4: i wanted to write anoter test to test exactly errors with certs and ignore these errors in other tests , but i can`t!

**Comment by xavier-taylor** [comment]
I'm also stuck because of this issue. Seems a bit rough that you just ignored rusekr's arguments, after you invited him to make them...

**Comment by rusekr** [comment]
It the end I patched fork of superagent with pull request to it of another user and set it as dependency of my fork of chai-http. and with this fork depending on fork as dependency of resulting project i managed to get what i needed. ggg

p.s. for now I am using jest

**Comment by keithamus** [comment]
We're looking to re-work this module to move away from superagent, and instead move to using Web Platform base primitives like `fetch`. This will take some time, because it's hard to find free time to work on this, but rest assured the comments are being listened to and we want to make things easier.

If you'd like to get involved then we encourage it, the more maintainers projects like this have the more likely they are to stay alive!
