### ISSUE TITLE
How does Chai-HTTP integrate with Sinon in this situation?

### ISSUE THREAD

**Issue by MinhLu12** [chaijs/chai-http#181]
Here is the route I want to test:

```
app.post('/api/user', (req, res) => {

        dbService.replaceUserOnDuplicate(req.body, function returnResponse(insertedId) {
            if (insertedId === 0 || insertedId === req.body.id) {
                return res.sendStatus(200);                            
            }
            // TODO_MINH: Send an appropriate error to handle by the front-end
            return res.send({});
        });
    });
```
I can use chai-http to do something like this (psuedo-code):

```
it('test', function (done) {
            chai.request(server)
                .post('/api/user')
                .send({ user: SomeUserObject })
                .end(function (err, res) {
                    res.should.have.status(200);
                    done();
                });

        });
```
However, the api/users route makes a Database call. How would I use sinon to stub this method (replaceUserOnDuplicate) so that it returns a dummy response (like 0, or anything)?

Is it possible? I'm looking at the Chai-HTTP syntax and I see no room to insert any Sinon stubbed methods.

Thanks for your help!

**Comment by austince** [comment]
Hey @MinhLu12, trying to tackle some old issues. There is no great solution for what you're suggesting as `chai-http` is usually used for integration/end-to-end testing. You might be able to hack together a way to stub it out if you can export the `dbService` that is used by the server, but I think this is a bad idea.

What I'd suggest is to write [lower level tests](http://softwaretestingfundamentals.com/software-testing-levels/) that would help cover this functionality (and where sometimes it is warranted to stub). You should also be testing against a test database, usually best in a docker container, and then can do more of these end-to-end tests without worrying about messing up the db, though cleaning up each test's data is always best.
