### ISSUE TITLE
Node Security Advisory for dependecy

### ISSUE THREAD

**Issue by shoshi** [chaijs/chai-http#182]
There's a Node Security Advisory for `superagent`: https://nodesecurity.io/advisories/479

The fix is to "update to version 3.7.0 or greater." Would it be possible to bump the dependency version `3.3.0` up to `3.7.0` or higher?

**Comment by keithamus** [comment]
Hey @shoshi thanks for the issue!

Bumping to `3.7.0` sounds like a good idea. PRs welcome!

**Comment by loayg** [comment]
@LEQADA Thanks for the PR. 
@keithamus would it be possible to release since the last released version still has  the old vulnerable version. Thanks.

**Comment by austince** [comment]
I believe this was released with [4.0.0](https://github.com/chaijs/chai-http/releases/tag/4.0.0) :confetti_ball: , so closing this.
