### ISSUE TITLE
Agent Server not closing after tests

### ISSUE THREAD

**Issue by gswalden** [chaijs/chai-http#188]
Closely related to #178

Setup:
```
npm install chai chaijs/chai-http#master
```

Code that exits:
```js
const server = require('http').createServer((req, res) => {
  res.end('Hello World!');
});

const chai = require('chai');
chai.use(require('chai-http'));
const req = chai.request(server);
req.get('/').then(res => {
  console.log(res.text);
});
```

Code that hangs:
```js
const server = require('http').createServer((req, res) => {
  res.end('Hello World!');
});

const chai = require('chai');
chai.use(require('chai-http'));
const agent = chai.request.agent(server);
agent.get('/').then(res => {
  console.log(res.text);
});
```

Valid as of cee5dbd0216b20c8ddf8d98e5a9dd7a8d389addd.

**Comment by keithamus** [comment]
Thanks for issue @gswalden

I wasn't sure if it made sense to auto-close the server for `agent`, as it is used to store cookie data and made subsequent requests with that data. (Ideally servers should be stateless but this felt like less of a footgun than auto closing a server). If you disagree with this decision I'd love to hear more about your usecase

**Comment by gswalden** [comment]
Understood, if it's a design decision I can't say I have an issue. I will add a note to the README to close this out.

**Comment by keithamus** [comment]
Thanks @gswalden 👍
