### ISSUE TITLE
Server not closing

### ISSUE THREAD

**Issue by kennedyoliveira** [chaijs/chai-http#189]
Hello everyone, i'm new to chai and i'm having some difficulties to close the server after using it.

I'm following the example on the README: 

When passing an `app` to `request`; it will automatically open the server for
incoming requests (by calling `listen()`) and, once a request has been made
the server will automatically shut down (by calling `.close()`). If you want to
keep the server open, perhaps if you're making multiple requests, you must call
`.keepOpen()` after `.request()`, and manually close the server down:

```js
var requester = chai.request(app).keepOpen()

Promise.all([
  requester.get('/a'),
  requester.get('/b'),
])
.then(responses => ....)
.then(() => requester.close())
```
And i noticed that it doesn't work, looking at the source, the close function only close the server if the keepOpen is `false`, as is pointed here [close function](https://github.com/chaijs/chai-http/blob/cee5dbd0216b20c8ddf8d98e5a9dd7a8d389addd/lib/request.js#L228).

What is the correct way of keeping the server open and closing manually?

**Comment by kennedyoliveira** [comment]
As a workaround, i created the server myself, and instead of using the app to create the request, i use the server and manually close it, but would be interesting not having to do it and relaying only on `chai-http`.

**Comment by keithamus** [comment]
Hey @kennedyoliveira thanks for the issue.

Are you using the latest version from `npm` or installing from `master`?

**Comment by kennedyoliveira** [comment]
I'm installing from master, and the line i pointed is from the master too.

**Comment by keithamus** [comment]
It's worth noting that it was a design decision to keep a server that ran from an agent open by default (see https://github.com/chaijs/chai-http/blob/cee5dbd0216b20c8ddf8d98e5a9dd7a8d389addd/lib/request.js#L318-L320).

The reason for having Agents keep the server open is (for better or worse) shutting the server down may cause issues with state that a server may maintain. While it is certainly true that servers should rely on no state, I felt as though practically speaking in my experience is that is not true; and servers can change state between boots, leading to potential footguns when trying to make new requests with an Agent. 

If you feel differently about this, please do let us know! We should get this feature right!

**Comment by kennedyoliveira** [comment]
Hey @keithamus, i didn't quite understand your answer, i agree with you about keeping the server open, seems indeed a good design, my question was about the specific function `close` which doesn't close the server when called, unless the `keepOpen` flag is set to false. I just want to understand the best / idiomatic way of keeping the server open during a test and closing on the end, with a `after` block.

Quoting the example in the README again:

```
var requester = chai.request(app).keepOpen()

Promise.all([
  requester.get('/a'),
  requester.get('/b'),
])
.then(responses => ....)
.then(() => requester.close())
```

The line `requester.close()` doesn't do anything, because the `keepOpen` sets the flag to true.

I didn't use the `TestAgent` you mentioned, how it works?

Thanks for you time!

**Comment by keithamus** [comment]
Ah yes! Sorry, I misread the original comment. This looks like a bug and should absolutely be fixed, with some tests to ensure that it doesn't regress with future changes.

If you'd like to make a pull-request that addresses this, I'd love to review it and get it merged in before the next release!

**Comment by kennedyoliveira** [comment]
No problem, i sure could, i'll check the source and look what can be done, if you can give me any hint, because as i stated, i just started using it so i could may introduce some unwanted behavior haha.

Thank you!

**Comment by keithamus** [comment]
I think:

https://github.com/chaijs/chai-http/blob/cee5dbd0216b20c8ddf8d98e5a9dd7a8d389addd/lib/request.js#L236-L238

Needs to change to 

```js
on('end', function () {
  if (keepOpen === false) obj.close()
})
```

and https://github.com/chaijs/chai-http/blob/cee5dbd0216b20c8ddf8d98e5a9dd7a8d389addd/lib/request.js#L228-L231

needs to change to 

```js
  obj.close = function(callback) {
    if (server && server.close) {
      server.close(callback);
    }
    return this
}
```

**Comment by melkarm** [comment]
Hello,

This still happens to me with v3.0.0 through npm.

Regardless or whether I use 
`const agent = chai.request(app)`
or 
`const agent = chai.request.agent(app)`,

I get `close is not a function` when calling `agent.close()`.

Anything I am doing wrong?

**Comment by willchb** [comment]
Hello,

This is fixed in master since https://github.com/chaijs/chai-http/commit/3d7ab70b38518c09b3ab4e961134664dfd0a3850

@melkarm, In 3.0.0 you could call `agent.app.close()` instead.

**Comment by ken624** [comment]
I have same problem here. In description in [3d7ab70](https://github.com/chaijs/chai-http/commit/3d7ab70b38518c09b3ab4e961134664dfd0a3850), it says `This automatically closes server connections after making a request`. But for me it is not closing the server after test done. 

Also if I use `chai.request(app)`, it gives error. 

```js
const requester = chai.request(app)
requester.close()
```
This throws error:  `requester.close is not a function`
If I do this
```js
const requester = chai.request(app)
requester.app.close()
```
This throws error: `cannot read property 'close' of undefined`
So I have to do this
```js
const requester = chai.request.agent(app)
requester.app.close()
```
This doesn't throw error, but it doesn't close server neither.

**Comment by rkmax** [comment]
In my case I found the problem, recent mocha's version aren't exiting the process by default (like the oldest one), is necessary the flag `--exit` if not will keep running

**Comment by E314c** [comment]
@rkmax while that's a workaround in telling mocha "please just force quit anything when you think you've finished with the tests", it doesn't fix the underlying problem that there's an un-finished process in the event loop

**Comment by BlueWater86** [comment]
I've hit this issue too and will be submitting a pull request to get it fixed. The problem begins when passing an already listening server into chai-http's request.

The logic in the code below says: if app parameter is a function, pass it as a parameter to http.createServer() which creates a new server ignoring the one that you've passed in.

From here you end up with your server listening on one port and a duplicate chai-http server listening on another port. Because the duplicate server is a variable scoped to the function you can not close it in external code.

`module.exports = function (app) {

  /*!
   * @param {Mixed} function or server
   * @returns {Object} API
   */

  var server = ('function' === typeof app)
      ? http.createServer(app)
      : app
    , obj = {};`

**Comment by BlueWater86** [comment]
I take back my previous comment agreeing that this is a bug. The problem was in my code not in the logic of chai-http.

Yes there was a duplicate server bound to a port but this was because I was exporting my express app from server.js and not my listening server.

Server.js, don't do:
```
let app = express();
app.listen(config.port);
module.exports = app
```

Instead:
```
let app = express();
module.exports = app.listen(config.port);
```

**Comment by trdvangraft** [comment]
@BlueWater86 thank you very much really helped me out, the solution worked.

**Comment by wombolo** [comment]
> I take back my previous comment agreeing that this is a bug. The problem was in my code not in the logic of chai-http.
> 
> Yes there was a duplicate server bound to a port but this was because I was exporting my express app from server.js and not my listening server.
> 
> Server.js, don't do:
> 
> ```
> let app = express();
> app.listen(config.port);
> module.exports = app
> ```
> Instead:
> 
> ```
> let app = express();
> module.exports = app.listen(config.port);
> ```

Authentic solution. Works for me. Thanks

**Comment by catiaraminhos** [comment]
> I take back my previous comment agreeing that this is a bug. The problem was in my code not in the logic of chai-http.
> 
> Yes there was a duplicate server bound to a port but this was because I was exporting my express app from server.js and not my listening server.
> 
> Server.js, don't do:
> 
> ```
> let app = express();
> app.listen(config.port);
> module.exports = app
> ```
> 
> Instead:
> 
> ```
> let app = express();
> module.exports = app.listen(config.port);
> ```

It really worked! Thanks!
