### ISSUE TITLE
A package with new version

### ISSUE THREAD

**Issue by raciasolvo** [chaijs/chai-http#192]
Hello!
Please create new package 3.0.1. I have some troubles with `"superagent": "^2.0.0"` from package 3.0.0 because `npm` installs `superagent` with version `<3.0.0`.
I am installing chai-http from master now.

**Comment by marcos-diaz** [comment]
I there any reason for this not happening?

**Comment by marcos-diaz** [comment]
this can be closed since 4.0.0 is out
