### ISSUE TITLE
Secure Cookies cannot be validated

### ISSUE THREAD

**Issue by mindhaq** [chaijs/chai-http#193]
I'm using chai-http for writing functional tests on an external HTTPS interface. I want to check if the response contains certain Cookies.

        it('it should send XSRF token in cookie', () => {
            const agent = chai.request.agent("https://example.com");
            return agent.get('/r')
                .then(res => {
                    expect(res).to.have.cookie('XSRF-TOKEN');
                })
        });

This stopped working when the server sent the Cookies with a `secure` flag.

    AssertionError: expected cookie 'XSRF-TOKEN' to exist

The cookie is in the header and can be read from there, just not from the `CookieJar`.

I can see that `CookieAccessInfo.All` is [used](https://github.com/chaijs/chai-http/pull/128/commits/2ae97dd4b36df4e7b9f2089eaf7a491d65b96401). This, however, only works with Cookies without the secure flag (which might be a problem in CookieJar as well, I'll open an issue there as well).

It would help me if I could provide a custom CookieAccessInfo for my tests.

**Comment by mindhaq** [comment]
maybe #192 would already help me.

**Comment by mindhaq** [comment]
ok, current master does not have this problem.

really time for a new release :)

**Comment by keithamus** [comment]
Thanks @mindhaq. I hope to get a new release out before the end of the year. We need to get some things done first though.

**Comment by thw0rted** [comment]
Hello from the future, @mindhaq and @keithamus .  I'm still having this problem using `chai-http` v4.3.0.

My usage is slightly different from the OP (`app = new MyApplication(); agent = new chai.request.agent(app);`) but the symptom is the same.   If I set the cookie using `res.cookie("SOME_COOKIE", "VALUE", {secure: true})`, then redirect to another route, it isn't present when the handler for the second route goes looking for it, but if I remove `secure` then it is.

When was this supposed to be fixed?  Could it have regressed?  Do I need to do something special to make the agent run as HTTPS, or ignore the Secure flag?
