### ISSUE TITLE
application/json

### ISSUE THREAD

**Issue by eino-makitalo** [chaijs/chai-http#201]
when trying to use this with command like...
chai.request(server).post('/api/v1/logic/add').
        .send({ position:'below',
            country:'com',
            target: uuidtarget
            uuid: uuid
            });
I cant find to specify content-type: application/json   ... it is always sending text/plain which breaks my test

**Comment by chrismclarke** [comment]
same problem here, tried with .type("form") however it tries to flatten nested json arrays which then gives problems for me later.

**Comment by chrismclarke** [comment]
Actually never mind, I see this is an issue with [superagent ](https://github.com/visionmedia/superagent/issues/860)

**Comment by chrismclarke** [comment]
Resolved by chaining `.type("json")` to the request. Assume this should also work for @eino-makitalo

**Comment by austince** [comment]
@eino-makitalo, did specifying the `type`  fix your issue?
