### ISSUE TITLE
keepOpen is not a function 

### ISSUE THREAD

**Issue by ioanniswd** [chaijs/chai-http#207]
Tried to keep server running to test multiple consecutive requests, copied test from test/request.js but getting:

TypeError: chai.request(...).keepOpen is not a function

My code:
```
"use strict";

const chai = require('chai');
let chaiHttp = require('chai-http');
chai.use(chaiHttp);
const expect = chai.expect;

var server = require('http').createServer(function(req, res) {
  res.writeHead(200, {
    'content-type': 'text/plain'
  });
  res.end('hello world');
});

var requester = chai.request(server).keepOpen();
```

**Comment by HanHyeoksu** [comment]
+1

**./test/test.js**
```js
const chai = require('chai');
const chaiHttp = require('chai-http');
chai.use(chaiHttp);

// my server is created by koa2
const server = require('../app');

describe('Test', () => {
  it('just testing', () => {
    chai.request(server).keepOpen()
    .get('/api/hello')
    .end((err, res) => {
      if (err) {
        console.error(err);
      }

      console.log('result:', result);
    });
  });
});
```

**package.json**
```json
{
  "scripts": {
    "test": "mocha --recursive"
  },
  "dependencies": {
    "chai": "^4.1.2",
    "chai-http": "^3.0.0",
    "mocha": "^5.0.2",
  },
}
```

**run**
```shell
$ yarn test
```

**result**
```
TypeError: chai.request(...).keepOpen is not a function
```

node: v8.9.4
yarn: v1.3.2

**Comment by slavik-m** [comment]
+1

**Comment by HanHyeoksu** [comment]
I figured out why `keepOpen` is not shown.
According to the commit log and release history, the code that has `keepOpen` is not released on npm yet.
`keepOpen` is added about 4months ago, but the chai-http was released at jun 10th 2016.

**Comment by Zikoel** [comment]
According with npm page I have found that `chai-http` is on version 4.0.0 updated 19 days ago. So after updating version on my `package.json` to the right `chai-http` I  can found the `keepOpen` function and all work well!

**Comment by keithamus** [comment]
I'll close this as this is part of chai-http@4. Anyone who lands on this issue should upgrade.

Thanks everyone!
