### ISSUE TITLE
Uncaught TypeError: Cannot read property 'writeQueueSize' of null

### ISSUE THREAD

**Issue by apoguy** [chaijs/chai-http#212]
I'm running some tests using Mocha, Chai and Chai Http.

Right now I am facing the following issue:

>  1 failing
> 
>   1) Request Tests
>        "after all" hook:
>      Uncaught TypeError: Cannot read property 'writeQueueSize' of null
>       at TLSSocket.Socket._writeGeneric (net.js:786:33)
>       at TLSSocket.Socket._writev (net.js:794:8)
>       at doWrite (_stream_writable.js:395:12)
>       at clearBuffer (_stream_writable.js:501:5)
>       at TLSSocket.Writable.uncork (_stream_writable.js:313:7)
>       at connectionCorkNT (_http_outgoing.js:682:8)
>       at _combinedTickCallback (internal/process/next_tick.js:135:11)
>       at process._tickCallback (internal/process/next_tick.js:180:9)

Here's the code of my test:

```
const chai = require('chai');
const chaihttp = require('chai-http');
chai.use(chaihttp);
const expect = chai.expect;
const fuzzer = require('fuzzer');

describe('Fuzz Test', () => {

        describe('fuzzing login page with 1000 username/password permutations', () => {

            fuzzer.seed(0);

            it('should respond with 403 / invalid csrf token', () => {

                for(var i=0; i <= 1000; i++){

                    chai.request(app)
                        .post('/login')
                        .send({
                            username: fuzzer.mutate.string('fuzzfromhere'),
                            password: fuzzer.mutate.string('fuzzfromhere')
                        })
                        .then(resp => {
                            if (resp.status != 403 && resp.status != 429) throw code;
                        })
                        .catch(err => {
                            throw err;
                        });

                }

            });

        });

});
```
Other tests using Chai Http are working fine. Problem apparently is when you perform this 1000 requests.

**Comment by keithamus** [comment]
Hey @apoguy thanks for the issue.

I dont think this is a bug with Chai-http - you are likely exhausing Node's socket pool. You'll want to either batch these, or run them in serial. Serial execution is pretty trivial, just turn this into an async function and await `chai.request` - like so:

```diff
@@ -10,11 +10,11 @@
 
             fuzzer.seed(0);
 
-            it('should respond with 403 / invalid csrf token', () => {
+            it('should respond with 403 / invalid csrf token', async () => {
 
                 for(var i=0; i <= 1000; i++){
 
-                    chai.request(app)
+                    await chai.request(app)
                         .post('/login')
                         .send({
                             username: fuzzer.mutate.string('fuzzfromhere'),
```

This might run a little slow as each test would need to be set up and subsequently paired down. Alternatively you can batch these requests into, say, 100 at a time by accumulating them and running Promise.all:

```diff
@@ -10,11 +10,12 @@
 
             fuzzer.seed(0);
 
-            it('should respond with 403 / invalid csrf token', () => {
+            it('should respond with 403 / invalid csrf token', async () => {
+                let testBatch = []
 
                 for(var i=0; i <= 1000; i++){
 
-                    chai.request(app)
+                    testBatch.push(chai.request(app)
                         .post('/login')
                         .send({
                             username: fuzzer.mutate.string('fuzzfromhere'),
@@ -25,7 +26,12 @@
                         })
                         .catch(err => {
                             throw err;
-                        });
+                        }))
+
+                    if (i % 100 === 0) {
+                      await Promise.all(testBatch)
+                      testBatch = []
+                    }
 
                 }
```

Hopefully this helps. I'm going to close this issue as I'm quite sure this isn't a chai-http bug, but if the above solutions don't work for you then please let me know and we can re-open this. Thanks!
