### ISSUE TITLE
Display text of HTTP response upon exception

### ISSUE THREAD

**Issue by cdupont** [chaijs/chai-http#216]
I'm using chaiHttp to test an API:

```
describe('Get Sensors', () => {
  it('sensors are returned as an array', async () => {
     let res = await chai.request(baseUrl).get(`/test`)
     res.should.have.status(200);
  });
});
```

This works well, except when an exception happens:

```
AssertionError: expected { Object ...} to have status code 200 but got 500
  + expected - actual

  -500
  +200

  at Proxy.<anonymous> (node_modules/chai-http/lib/http.js:83:10)
  at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
  at Context.it (test/sensor.test.js:47:23)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:160:7)
```

The error message is not so useful to debug the API. How can I display also the body of the HTTP response error? It usually contains more explanation of the error. I could wrap all my tests in try/catches, but this seem cumbersome.

**Comment by cdupont** [comment]
I added this in function status of http.js:

`'expected #{this} to have status code #{exp} but got #{act} with message: ' + this._obj.text`

It gives good results.

**Comment by damianb** [comment]
To be quite honest, this is more of an issue of your application's design than it is of the library.  If your application throws an HTTP 500 response suddenly, it should be covered by implementing suitable logging of application errors.  Further, if any actually relevant information (e.g. stack trace of the error) were to be available in the response output, that would constitute an information disclosure class of vulnerability and should be suppressed.

**Comment by cdupont** [comment]
Hi @damianb,
that's a good point, however my application has a lot of log traces. A chai test can lead to many API calls in my app. It's not easy to pin point the right message corresponding to the return code message. The stack trace is not included in the returned error code response, as you correctly point out that would be internal leaking. But sometime the HTTP code alone is not enough to debug and is accompanied with some message, for instance 400: "missing field XX in POST message body".
It would be nice if chai had some options to display the error messages easily. I think some primitives could be added to allow that, for example:
```
res.should.have.status2(200);  // display the body in case of error
res.should.have.status(200).otherwise.displayErrorBody; // display the body in case of error
```
Just thinking.

**Comment by vieiralucas** [comment]
@cdupont You can overcome that by checking the body before the status.
Like:
```js
const chai = require('chai')
const chaiHttp = require('chai-http')
const express = require('express')

chai.use(chaiHttp)

const app = express()

app.get('/ping', (req, res) => {
  res.status(400).json({ reason: 'no reason at all' })
})

it('cool test', async () => {
  const res = await chai.request(app).get('/ping')

  chai.expect(res.body).to.equal('pong') // check body first
  chai.expect(res).to.have.status(200)
})
```

If you write your test like this your test will fail because the `body` has an unexpected value. That way you would be able to see the actual body in the diff.

```
  1) cool test

  0 passing (43ms)
  1 failing

  1) cool test:
     AssertionError: expected { reason: 'no reason at all' } to equal 'pong'
      at Context.it (test.js:16:28)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by cdupont** [comment]
Hi @vieiralucas, good idea.
However, in case of success (200), the body can be variable; so it's hard to predict. 
What I really need is:
case 200 -> display nothing
case other -> display error code + error body

Is there a way to add some custom functions in my code? I want to add this:
```
   Assertion.addMethod('status', function (code) {
     var hasStatus = Boolean('status' in this._obj || 'statusCode' in this._obj);
     new Assertion(hasStatus).assert(
         hasStatus
         , "expected #{act} to have keys 'status', or 'statusCode'"
         , null // never negated
         , hasStatus // expected
         , this._obj // actual
         , false // no diff
     );
 
     var status = this._obj.status || this._obj.statusCode;
 
     this.assert(
         status == code
       , 'expected #{this} to have status code #{exp} but got #{act} **with message: ' + this._obj.text**
       , 'expected #{this} to not have status code #{act}'
       , code
       , status
     );
   });
```
