### ISSUE TITLE
Impossible to specify passphrase argument in GET http call

### ISSUE THREAD

**Issue by w7089** [chaijs/chai-http#222]
Couldn't find how to specify passphrase in client certificate in chai-http or superagent docs.
So, it seems impossible to make the below call using chai-http...

    curl -k --key [key_path] --cert [cert-path]:secret 'https://127.0.0.1/url'
The following code returns error:

> Error: error:0906A068:PEM routines:PEM_do_header:bad password read

I guess it's because of missing passphrase argument.

```
    let chai = require('chai');
    let chaiHttp = require('chai-http');
    
    let should = chai.should();
    var expect = chai.expect;
    
    chai.use(chaiHttp);
    
    // load certificates
    let fs = require('fs')
    let key = fs.readFileSync(__dirname + '/user.key')
    let cert = fs.readFileSync(__dirname + '/user.crt')
    
    describe('client certificate call', () => {
        it('should return data', () => {
            chai.request('https://127.0.0.1')
            .get('/url')
            .key(key)
            .cert(cert, 'secret')
            // .passphrase('secret')
            .end((err, res) => {
                    res.should.have.status(200);
                    done();
                });
            });
    
    })
```

**Comment by austince** [comment]
Hi @w7089, I'm not sure if your `curl` call can be translated into something that `superagent` can handle, but I'm going to close this as it involves `superagent` and not `chai-http`. It might be good to open [over there](https://github.com/visionmedia/superagent/issues) if you haven't found a good solution.
