### ISSUE TITLE
Trying to use agent throws an error TypeError: agent.request is not a function

### ISSUE THREAD

**Issue by kvarik** [chaijs/chai-http#227]
Here's code:
`let chai =  require('chai'),
  chaiHttp = require('chai-http');
chai.use(chaiHttp);
let agent = chai.request.agent(host);
`

Error: TypeError: agent.request is not a function

Node 10.10, Mocha 5.2.0, Chai 4.1.2, Chai-Http: 4.2.0

**Comment by austince** [comment]
Hi @kvarik, yes `Agent.request` is not a function. It is an instance of [`supertest`](https://github.com/visionmedia/superagent), which has methods like `get`, `post`, etc. but not `request`.

**Comment by kvarik** [comment]
@austince but how does it correspond with documentation? I simply copypasted code from docs and changed var to let.
