### ISSUE TITLE
err in .end(funtcion(err, res)) not being set?

### ISSUE THREAD

**Issue by bgSosh** [chaijs/chai-http#229]
Should err be set when the response contains an http code of 4xx/5xx?  I'm seeing err === null when getting these http codes in responses.

**Comment by austince** [comment]
Hi @bgSosh, as of [4.0.0](https://github.com/chaijs/chai-http/releases/tag/4.0.0), this library no longer reports errors based on http codes. Please see the release notes for how to migrate.
