### ISSUE TITLE
Make it easier to see from the docs that "DELETE" method is .del

### ISSUE THREAD

**Issue by kiwi-koder** [chaijs/chai-http#231]

**Comment by kiwi-koder** [comment]
Edit... Ok I was getting confused... It was just .del( that I needed!

**Comment by vieiralucas** [comment]
Hello @kiwi-koder thanks for your issue, do you have any suggestions on how we could do that?

**Comment by austince** [comment]
I think having this indexed in the issues should help the majority of people who run into this issue in the future. This seems like another instance that supports [moving to a more standard HTTP request library. ](https://github.com/chaijs/chai-http/issues/203)
