### ISSUE TITLE
Property 'status' does not exist on type 'Assertion'

### ISSUE THREAD

**Issue by khusamov** [chaijs/chai-http#242]
Hello! How do I write TypeScript code correctly?

`error TS2339: Property 'status' does not exist on type 'Assertion'.`

```typescript
describe('EircHttpProxy', function() {
	it('Test 1 + 1', done => {
		request(proxy)
			.post('/pir_war/rs/DebtorInformationResource/getLawCaseProceedings')
			.end((req: SuperagentRequest, res: SuperagentResponse) => {
				res.should.have.status(200); // ERROR
			});
	});
});
```

Also I can not understand how to fix the following error:
`error TS2305: Module '"chai"' has no exported member 'request'.`

```typescript
import {assert, use, request} from 'chai';
```

**Comment by austince** [comment]
Hi @khusamov, just looking over your example, it looks like something you need to do is:

```ts
import chai = require('chai');
import chaiHttp = require('chai-http');

chai.should();
chai.use(chaiHttp);

describe('EircHttpProxy', function() {
	it('Test 1 + 1', done => {
		chai.request(proxy) // note the chai.
			.post('/pir_war/rs/DebtorInformationResource/getLawCaseProceedings')
			.end((req: SuperagentRequest, res: SuperagentResponse) => {
				res.should.have.status(200); // ERROR
                                done(); // if you are using done, must call it or the runner will never exit
			});
	});
});
```

I'd know better if you'd share your `chai` setup / plugins. It also seems like maybe you'd benefit from reading through the [Chaijs Guide](https://www.chaijs.com/guide/) which gives a good configuration overview (and is equally as applicable to TypeScript!).

**Comment by austince** [comment]
Going to close this as it is not an issue with `chai-http` - let me know if this helped you @khusamov.
