### ISSUE TITLE
cookie() doesnt assert on Agent cookies

### ISSUE THREAD

**Issue by svallory** [chaijs/chai-http#25]
Hi, I'm trying to use the `cookie` method and I'm getting the following error:

`TypeError: Cannot call method 'split' of undefined at [object Object].<anonymous>`
[`(http.js:307:48)`](https://github.com/chaijs/chai-http/blob/1.0.0/lib/http.js#L307)

Here is my code:

``` js
var agent = chai.request.agent(app)

describe('POST /logout', function() {
  it('Should logout the user', function() {
    return agent.get('/api/v1/users/me')
                .then( function(res) {
                  expect(res).to.have.cookie('connect.sid')
                });
  });
});
```

I'm using v1.0.0

**Comment by keithamus** [comment]
Hey @svallory. Do you have anything for this? If not I might just take a crack at it over the weekend.

**Comment by svallory** [comment]
@keithamus Sorry, I don't. I simply created a new agent for each test and that solved it for me. Also, I'm really really busy and the message refactoring on chai is still hanging before this issue :/

**Comment by yashsriv** [comment]
I'd like to work on this.
