### ISSUE TITLE
Documentation is not very clear about how to set request headers

### ISSUE THREAD

**Issue by theodorewahle** [chaijs/chai-http#254]
I think it would be good to include in the documentation explicitly that `.set(key, value)` is how you set a request header. May I specify this in the docs?

**Comment by keithamus** [comment]
Hey @theodorewahle thanks for the issue!

Please feel free to raise a PR to add this to the documentation!

**Comment by theodorewahle** [comment]
Hey @keithamus, here is my [PR](https://github.com/chaijs/chai-http/pull/256)

**Comment by austince** [comment]
Closed with #256 :confetti_ball:
