### ISSUE TITLE
Cookies are not being properly set in requests

### ISSUE THREAD

**Issue by not-a-seagull** [chaijs/chai-http#260]
My code that is being tested. This is express.js code.

```js
  // process a login request
  app.post("/process-login", async function(req: express.Request, res: express.Response) {
      // user authentication happens here

      // add user to session table
      const id = sessionTable.addSession(user, false);
      res.cookie("sessionId", id, { maxAge: 8640000 * 8 });
      res.redirect("/");
  });
```

Here is a test that I am using:

```js
getServer().then((serv) => {
  server = serv;
  done();
});

// later...
chai.request(server).post("/process-login").send(userData).end((err, res) => {
  expect(err).to.be.null;
  expect(res).to.redirect;
  expect(res).to.have.cookie("sessionId");
  done();
});
```

The third assertion (expect res to have cookie) fails, even though the cookie is set here.

**Comment by austince** [comment]
Hi @not-a-seagull, I think your problems should be solved by using the `Agent`. Please see: https://github.com/chaijs/chai-http/issues/98#issuecomment-223531629

Will reopen if this is not the case.

**Comment by not-a-seagull** [comment]
I tried using agents but I'm still having issues.

```
        const agent = chai.request.agent(server);
        agent.post("/process-login").send(userData).end((err, res) => {
          expect(err).to.be.null;
          expect(res).to.redirect;
          expect(res).to.have.cookie("sessionId");
          done();
        });
```

This results in:

```Uncaught AssertionError: expected cookie 'sessionId' to exist```

I should note that, when I use my web browser to access the server, the cookie is successfully set and used.

**Comment by austince** [comment]
Can you create a small reproducable code sample / repository? It will make it much easier for us to help

**Comment by not-a-seagull** [comment]
https://github.com/not-a-seagull/chai-http/tree/master/test

I forked and made a new test (`cookie-w-express.js`). It fails and is unable to access the cookie.

**Comment by austince** [comment]
I believe the issue is with your redirect - when the request is redirected after setting the cookie in `/set-cookie`, it is not forwarded along in the next response. 

I've modified the test in your branch to show this, and show that you can assert the first cookie on the agent if you would like. 

```js
const cookieParser = require("cookie-parser");
const express = require("express");

// setting up an app to test with
var app = express();
app.use(cookieParser());

app.post("/set-cookie", function (req, res) {
  res.cookie("myCookie", "test_value", { maxAge: 8640000 });
  res.redirect("/");
});

app.get("/", function (req, res) {
  const text = `This is a test\nCookie is ${req.cookies.myCookie}`;
  res.cookie('myCookie2', req.cookies.myCookie);
  res.type("text/plain");
  res.send(text);
});

describe("Testing express w/ cookies and chai", function () {
  it("Run request", async () => {
    const agent = chai.request.agent(app);
    const res = await agent.post("/set-cookie").send({});
    expect(res).to.redirect;
    expect(res).to.have.cookie('myCookie2')
    expect(agent).to.have.cookie('myCookie');
  });
});

```
