### ISSUE TITLE
drop old nodejs support

### ISSUE THREAD

**Issue by L2jLiga** [chaijs/chai-http#267]
Currently chai-http supports `node >= 4` and `node < 10` already EoL.

Are there any reasons to support such versions of node?

**Comment by keithamus** [comment]
Hey @L2jLiga thanks for the issue.

We tend to drop support for older EOL versions of Node once we have a reason to make a breaking major release. At current, we have no plans to make a major release - but there is an effort to drop SuperAgent (#203) which will require such a release - at which point we'll drop support for any EOL Node versions.

I'll close this, as there's nothing actionable in of this issue. We'll drop older versions when we cut a major release.
