### ISSUE TITLE
Missing `exit` option in the API documentation, and the NodeJS API

### ISSUE THREAD

**Issue by regaldisclaimer** [chaijs/chai-http#274]
I commented [here](https://github.com/mochajs/mocha/issues/3044#issuecomment-666218490) initially, but this seems to be an issue to be addressed, not just my inability to locate information.

The new `--exit` option in v4 is not incuded in the [API documentation](https://mochajs.org/api/mocha), and also seems to be missing from the[ JS runner](https://github.com/mochajs/mocha/blob/master/lib/mocha.js).

Is this an intentional omission, or should it be added in?

**Comment by austince** [comment]
hey @regaldisclaimer, is this issue meant for this repo? I sometimes mix up `chai` and `mocha` myself :)

**Comment by regaldisclaimer** [comment]
@austince ah, yes. you're right. I was browsing both repos, and must have clicked on the wrong tab. Sorry about that!
