### ISSUE TITLE
How do i POST xml request in chai?

### ISSUE THREAD

**Issue by sunilhrx** [chaijs/chai-http#279]
I want to post a request with XML request in chai

Here's my code:

describe('Test group', function() {
    var host = "http://myhost.com";
    var path = "/myPath";

    it('should send parameters to : /myPath POST', function (done) {
        chai
            .request(host)
            .post(path)
            .type('xml')
            .set('content-type', 'application/xml')
            .send({'<Name> Sunil/>'})
            .then(function (res) {
                expect(res).to.have.status(200);
            })
            .catch(function (err) {
                throw err;
            })
    })
})

Can someone help me with the correct code here?

**Comment by austince** [comment]
Hey @sunilhrx, `chai-http` is mostly a wrapper around `superagent`, so I'd suggest you look at the superagent docs, particularly the section about [serializing request bodies](https://visionmedia.github.io/superagent/#serializing-request-body).  You probably don't need to add a custom serializer, but from the examples it looks like the `send` method should receive a `string` for `application/xml` bodies.


```js
chai.request(host)
    // ...
    .post(path)
    .send('<Name> Sunil </Name>')
   // ...
```
