### ISSUE TITLE
App errors are swallowed

### ISSUE THREAD

**Issue by adborden** [chaijs/chai-http#29]
I'm trying to test an error condition in my app. First I'm adding middleware that throws and expect this test to pass because there is no error handler in the app. However, it just hangs because the end handler and `done` are never called. 

```javascript
 it('throws', function(done) {
      var app = express();
      app.use(function(req, res, next) {
        throw new Error('Test failed request.');
      });

      chai.request(app)
        .get('/foo')
        .end(function(err, res) {
          expect(err).to.be.ok;
          done();
        });
});
```

Is this the right setup? Seems odd that things can just hang.

**Comment by keithamus** [comment]
Hey @adborden thanks for the issue. Your code looks pretty good, but I think the key is what you're doing with Express - throwing errors inside an express route isn't canon; generally if you have an error you'd call `next(err)`. Also as you've no error handling middleware in place, I'm not exactly sure what Express would end up doing, does it error on your behalf? Or does it just 404 assuming that route couldn't fulfil its intent?

**Comment by adborden** [comment]
Yeah, I'm testing an unusual case. One would hope you're using middleware that doesn't throw in your app, but in case a third-party middleware throws unexpectedly, I want to make sure my code does the right thing and this is the beginnings of that test.

I believe without an error handler express returns a 500 response. Even if it just threw an uncaught exception and crashed the app, I would expect either my test to fail or for chai-http to bubble up the error or at least call the callback with a 500 response. Seems like chai-http is somehow swallowing it. I'm using mocha which would fail the test in the event of an uncaught exception.

I also want to point out if you change the code to be `next(err)`, it hangs in the same way. Hope this helps.

**Comment by keithamus** [comment]
@adborden what if you add logging throughout the test, to see which point it starts hanging at? Something like:

```js
 it('throws', function(done) {
      console.log(1);
      var app = express();
      app.use(function(req, res, next) {
        console.log(3);
        throw new Error('Test failed request.');
      });
      console.log(2);
      chai.request(app)
        .get('/foo')
        .end(function(err, res) {
          console.log(4);
          expect(err).to.be.ok;
          console.log(5);
          done();
          console.log(6);
        });
});
```

It's not pretty or elegant but it'll quickly show you which line is hanging.

**Comment by keithamus** [comment]
@adborden did you manage to successfully debug this?

**Comment by keithamus** [comment]
Hey @adborden - as this issue is over a year old, I think I'm going to close it. If you have the issue again, or want to comment more - please do so and I can reopen the issue.
