### ISSUE TITLE
Settings headers and delete requests

### ISSUE THREAD

**Issue by jenius** [chaijs/chai-http#30]
It seems like there's some sort of weird thing going on with the `del` method paired with the setting of any headers. Example:

```js
chai.request(app)
  .del("/any_url")
  .set('Any-Header', 'xxx')
  .res(function(res){ console.log(res); })
```

What's strage about this is that the test passes fully, hitting the right method with the right headers, but it does not hit the `console.log` and fails with the following error message:

```
TypeError: Object #<Test> has no method 'set'
```

If you want me to take a look into this and can push me in the right direction, would be happy to take a stab at it! It's really messing up my test suite :cry: 

**EDIT:** Same thing happens with `get`

**Comment by keithamus** [comment]
Thanks for the issue @jenius. Strange that you get that error - the Test class very clearly has a `set` method. Having said that I'm not sure it has a `res` method as your code example suggests.

By all means try to get a reduced test case going. Please try to supply more detail within the issue if you can and I'll try and push you in the right direction some more.

**Comment by jenius** [comment]
Hey sorry, figured it out. I was on an older version of the library, most recent release works great :grinning:
