### ISSUE TITLE
Update to superagent 1.0

### ISSUE THREAD

**Issue by pgrm** [chaijs/chai-http#34]
Hi, I wanted to know if there are any plans to update to Superagent 1.0. It has been released only few days ago, but I'm very interested in this fix: https://github.com/visionmedia/superagent/commit/8c3858a19f70a86cc2ade99070f4c709968e787b as I need to test if my API returns a `null` value or not.

**Comment by keithamus** [comment]
Sweet! Didn't know 1.0 was out. Feel free to submit a PR

**Comment by pgrm** [comment]
I've submitted a PR, please push it to NPM at your earliest convenience, thx

**Comment by inukshuk** [comment]
Is there anything holding this back or did you just forget to push to NPM? If there's work to be done I'd be glad to help land this update.

I noticed that responses with error codes like 400, 404 etc. are now returned as errors (and the properties like status do not seem to be available?), but otherwise all my tests continue to work when using the GitHub version (NPM still pulls the old superagent).

**Comment by keithamus** [comment]
Hey @inukshuk, @logicalparadox will need to update the .travis.yml for auto-publishing like we've done in other repos. As soon as that's done we can roll out a new release. I guess given your comments we'll mark it as a 2.0.0.

**Comment by inukshuk** [comment]
Awesome!

The SuperAgent [docs ](http://visionmedia.github.io/superagent/#error-handling) mention that the `err` objects returned for 4xx and 5xx responses ought to contain properties like `.status` or `.response`, but I do not see them when using the Promise API of chai-http. However, if I read your `.then` [implementation](https://github.com/chaijs/chai-http/blob/master/lib/request.js#L234) correctly the error object passed through should be that of SuperAgent — is that correct?

**Comment by inukshuk** [comment]
OK I figured it out: the properties were added in 1.1.0; the current release is already 1.2.0 so I would adjust the version number accordingly.

**Comment by keithamus** [comment]
Ok, I'll close this one now, and we'll release a 2.0.0 soon. Thanks @inukshuk and @pgrm
