### ISSUE TITLE
No export named `request`

### ISSUE THREAD

**Issue by torra** [chaijs/chai-http#342]
Currently, in the documentation in the [readme](https://github.com/chaijs/chai-http?tab=readme-ov-file#plugin), there is an example importing `request` from `chai-http`:
```
...
import {default as chaiHttp, request} from "chai-http";
...
```

However, there is no export named `request` in the currently available release in npm, which is 5.0.0:
```
SyntaxError: The requested module 'chai-http' does not provide an export named 'request'
```

There is a tagged 5.1.0 release in github - does that fix the issue? Are there plans to publish that release to npm?

**Comment by 43081j** [comment]
Good catch! 

My mistake. We did publish a 5.1.0 release but the ci workflow to release it to npm failed

I will sort it out 👍

**Comment by torra** [comment]
Great, thanks!

**Comment by torra** [comment]
Thanks for fixing this!

I believe I found two small typos in the README btw: https://github.com/chaijs/chai-http/pull/343/files
