### ISSUE TITLE
Issues sending certain mimeTypes with formdata

### ISSUE THREAD

**Issue by James1x0** [chaijs/chai-http#36]
Maybe a superagent issue, but I have a test that attaches a csv/xls/xlsx (all in separate tests) to send to a busboy route. Busboy interprets the csv as a file, but the xls/xlsx as a field (form field). I have also seen the same behavior with png files, but works with jpg. Sending from the browser works fine.
```javascript
// Works and interprets as file so I can pipe the data into a writeStream
chai.request(app)
  .post('/my-busboy-endpoint')
  .attach(fs.readFileSync('mycsvfile.csv'), 'mycsvfile.csv');

// Does not work and busboy interprets as a field
chai.request(app)
  .post('/my-busboy-endpoint')
  .attach(fs.readFileSync('myexcelfile.xls'), 'myexcelfile.xls');
```

**Comment by keithamus** [comment]
Hey @James1x0 thanks for the issue!

By the time you've called `post()` or one of the other HTTP-alike methods, you're in SuperAgent territory, so the `attach()` method is actually SuperAgent. However, `attach()` really just delegates to [FormData](https://github.com/felixge/node-form-data/blob/master/lib/form_data.js).

So ultimately it could be a bug with SuperAgent, or it could be a bug with FormData - or it could be a bug with busboy! 

I'd recommend debugging the raw requests that Node gets between your tests and your browser - you might find that highlights some different discrepancies and helps us get to the bottom of this.

**Comment by James1x0** [comment]
I'm thinking this is a superagent issue then. Busboy interprets the webkit form data boundaries as a file when coming from the browser, but not from the chai-http call. I'll link up an issue there.

**Comment by wreckah** [comment]
I have the same problem in my tests :(

**Comment by James1x0** [comment]
@wreckah Yeah, still haven't solved the issue. Just had to abandon tests for that section of the api. Meh.

**Comment by wreckah** [comment]
@James1x0 It was fixed in chai-http 2.0.1!

**Comment by James1x0** [comment]
@wreckah sweet! Thanks for the heads up

**Comment by keithamus** [comment]
@James1x0 could you confirm that 2.0.1 fixes this? And then i can gleefully close this issue :smile:

**Comment by keithamus** [comment]
As this is a year old, and @wreckah confirmed it is working, I'm just going to go ahead and close this. If anyone is still experiencing this issue please let me know and we can re-open it.
