### ISSUE TITLE
Pass error message?

### ISSUE THREAD

**Issue by dstroot** [chaijs/chai-http#39]
If I use Supertest it passes the error message in this scenario however Chai-HTTP does not; yet both are using Superagent 1.2.  Any ideas?

```js
  describe('GET /error/500', function () {
    it('should return a 500 error', function (done) {
      chai.request(app)
        .get('/error/500')
        .end(function (err, res) {
          expect(err).to.not.be.ok;
          // expect(err.message).to.equal('Internal Server Error');  <- Doesn't Work with Chai-HTTP
          expect(res).to.have.status(500);
          expect(res.type).to.equal('text/html');
          expect(res.text).to.contain('<span class="red">Testing 1, 2, 3!</span>');
          done();
        });
    });
  });
```

**Comment by keithamus** [comment]
@dstroot sorry for taking so long to get back to you - are you still having this issue? `.end` comes straight from SuperAgent so the API should be the same.

I'm going to close this issue for now, for bookkeeping - but if you are still having this issue let me know and I'll re-open it right away 😄
