### ISSUE TITLE
Calling .then() multiple times on the same promise has weird side effects

### ISSUE THREAD

**Issue by SamPlacette** [chaijs/chai-http#64]
I just spent an hour tracking down this problem... Calling `.then()` on a promise should cause a new promise to be returned. But chai-http modifies the original promise. This causes all sorts of problems when I actually try to use chai-http with a test runner which attaches its own handlers to a promises.

From chai-http/lib/request.js:
```
Test.prototype.then = function (onResolve, onReject) {
  if (!Test.Promise) {
    throw new Error('Tried to use chai-http with promises, but no Promise library set');
  }
  if (!this._promise) {
    var self = this;
    this._promise = new Test.Promise(function (resolve, reject) {
      self.end(function (err, res) {
        console.log('resolve on Request.end', !! err, !! res, onResolve, onReject)
        if (err) {
          reject(err);
        } else {
          resolve(res);
        }
      });
    });
  }
  this._promise = this._promise.then(onResolve, onReject);
  return this;
};
```

Sorry I don't have a unit test to demonstrate this problem, I just wanted to jot down this note quickly while it's fresh in my head, hopefully this will save someone else an hour of debugging...

**Comment by keithamus** [comment]
Hey @SamPlacette thanks for the issue.

How do you feel about spending a bit of time and making a PR for this? It seems like you've got the code down, so adding a unit test and making a PR will put you [in our hall of fame](https://github.com/chaijs/chai-http/graphs/contributors) and also comes with a million internet points :smile:

**Comment by SamPlacette** [comment]
Thanks for the quick reply @keithamus.

That code snippet wasn't a fix, I just copied and pasted the function where the problem exists.

I could put together a fix but I'm trying to meet some deadlines at the moment. If I submitted a PR how fast could you get a new release out into NPM?

**Comment by keithamus** [comment]
Ahhh I see what you mean now (I thought you meant Chai-HTTP was mutating the original promise, but its creating a new one each time). What exactly is the test library doing? What would you propose to fix it?

As for releasing - I have planned out a few hours of time to Chai, which is happening in about 12 hours from now - so I could be cutting a release of chai-http in about 18 hours, if everything goes to plan.

**Comment by SamPlacette** [comment]
The problem is this line:
`  this._promise = this._promise.then(onResolve, onReject);`
This line re-assigns the promise on the chai-http response object.

I believe this is an error because attaching a fulfillment handler to a promise should create a new promise, and should not modify the original promise.

More information about my use case:

I'm using cucumberjs. I haven't looked at the source code of that test runner but I imagine it does something like this:
```
testcase.given().then(testcase.when).then(testcase.then).catch(onErr)
```

I return a response object from the chai-http lib in order to ensure the assertion clause of my cucumberjs testcase does not run until the request has completed and a response is available.

My testcase looks something like this:

```
'use strict'

let helpers = require('../helpers')
let chai = require('chai')
let expect = chai.expect

module.exports = function () {

  var response

  this.Given(/^The service is available$/, function () {
    // This is an implicit given. Noop.
  })

  this.When(/^I request health status$/, function () {
    var client = chai.request(process.env.AUT_URL)
    response = client.get('/v1/_status')
    return response
  })

  this.Then(/^I receive a 200 "OK" response$/, function () {
    return response.then(function (repr) {
      expect(repr.status).to.equal(200)
      expect(repr.statusText).to.equal('OK')
    })
  })
}
```

**Comment by keithamus** [comment]
I think re-assigning the promise is kind of necessary. Hopefully [this little jsbin can illustrate my point](https://jsbin.com/xegamidita/1/edit?js,console):

```js
/* jshint esnext: true */
console.log('a...');
var a = Promise.resolve(1)
  .then((v) => console.log('a:'+v) || 2)
  .then((v) => console.log('a:'+v) || 3)
  .then((v) => console.log('a:'+v));

console.log('b...');
var b = Promise.resolve(1);
b.then((v) => console.log('b:'+v) || 2);
b.then((v) => console.log('b:'+v) || 3);
b.then((v) => console.log('b:'+v));

console.log('c...');
var c = Promise.resolve(1);
c = c.then((v) => console.log('c:'+v) || 2);
c = c.then((v) => console.log('c:'+v) || 3);
c = c.then((v) => console.log('c:'+v));
```

The log output:

```js
"a..."
"b..."
"c..."
"a:1"
"b:1"
"b:1"
"b:1"
"c:1"
"a:2"
"c:2"
"a:3"
"c:3"
```

I'll need to take a peek at how cucumber works, but it _should_ be checking to see if `response` is a "thenable" (has a callbable `then` function) which is what all promise libs do. Some more investigation needs to be done here methinks.

**Comment by SamPlacette** [comment]
Promises should be immutable. See https://www.google.com/search?q=javascript+promises+are+immutable

If an object supports the promise interface by exposing a `then()` method, that object must also support the immutable nature of promises.

This makes for a convenient test case for illustrating that problem. Here's what that might look like:

```
var firstPromise = chai.request('http://foo.com').get('/bar')
var secondPromise = firstPromise.then(function (response) { console.log('got response', response) } )
expect(secondPromise).not.toEqual(firstPromise)
```

**Comment by keithamus** [comment]
By re-assigning `this._promise`, chai-http's api maintains the immutability - for all intents and purposes. This sounds pretty backward - that mutating the internal state of a request object somehow makes it immutable, but it rings true because the _Promise API surface_ retains its immutability. To put it another way, Promises are immutable because `Promise.prototype.then()` returns a new Promise. So does `Test.prototype.then()`.

**Comment by keithamus** [comment]
[here's the relevant code for cucumber-js btw](https://github.com/cucumber/cucumber-js/blob/f4bdd17388893523553d2a157feb18673e10dab8/lib/cucumber/support_code/step_definition.js#L136-L145) - it essentially does what I would expect - `if (typeof result.then === 'function') result.then(resolve, reject)`

**Comment by SamPlacette** [comment]
I don't have time to follow up on this right now. I want to reiterate that this library behaves differently from other promise libs leading to unexpected side effects.

For anyone else going through this problem, I was able to work around the problem by directly referencing the `_promise` property on the response.

**Comment by keithamus** [comment]
@SamPlacette I think your test suite is failing because `.then()` is being called multiple times, but the output isn't being carried over.

You say this is your test case:

```js
'use strict'

let helpers = require('../helpers')
let chai = require('chai')
let expect = chai.expect

module.exports = function () {

  var response

  this.Given(/^The service is available$/, function () {
    // This is an implicit given. Noop.
  })

  this.When(/^I request health status$/, function () {
    var client = chai.request(process.env.AUT_URL)
    response = client.get('/v1/_status')
    return response
  })

  this.Then(/^I receive a 200 "OK" response$/, function () {
    return response.then(function (repr) {
      expect(repr.status).to.equal(200)
      expect(repr.statusText).to.equal('OK')
    })
  })
}
```

Let's just look at the source of Chai-HTTP again:

```js
Test.prototype.then = function (onResolve, onReject) {
  if (!Test.Promise) {
    throw new Error('Tried to use chai-http with promises, but no Promise library set');
  }
  if (!this._promise) {
    var self = this;
    this._promise = new Test.Promise(function (resolve, reject) {
      self.end(function (err, res) {
        console.log('resolve on Request.end', !! err, !! res, onResolve, onReject)
        if (err) {
          reject(err);
        } else {
          resolve(res);
        }
      });
    });
  }
  this._promise = this._promise.then(onResolve, onReject);
  return this;
};
```

So the first `then()` calls `self.end()` and resolves to the response object.

Where this falls down is the underlying code of Cucumber which is nuking the resolved object.

Let me highlight a chunk of your test case:


```js
    response = client.get('/v1/_status')
    return response
  })

  this.Then(/^I receive a 200 "OK" response$/, function () {
    return response.then(function (repr) {
```

This is basically doing:

```js
response.then(function () { codeCallback(); /* return undefined!*/ }).then(function (repr)...)
         ^                                                            ^
         ┃                                                            ┖ This is your .then() call.
         ┃
         ┖━ This is from cucumber.js
```

The problem here is that cucumber.js is not returning any value from the responses original promise - which is why (I assume) your test is failing. The fix, is to do this:

```js
'use strict'

let helpers = require('../helpers')
let chai = require('chai')
let expect = chai.expect

module.exports = function () {

  var repr

  this.Given(/^The service is available$/, function () {
    // This is an implicit given. Noop.
  })

  this.When(/^I request health status$/, function () {
    var client = chai.request(process.env.AUT_URL)
    response = client.get('/v1/_status')
    return response.then(function (r) { repr = r })
  })

  this.Then(/^I receive a 200 "OK" response$/, function () {
    expect(repr.status).to.equal(200)
    expect(repr.statusText).to.equal('OK')
  })
}
```

Alternatively, you could file an issue with CucumberJS, asking them to return the given value in their promise callback - in other words change [step_definition.js#L107](https://github.com/cucumber/cucumber-js/blob/f4bdd17388893523553d2a157feb18673e10dab8/lib/cucumber/support_code/step_definition.js#L107) from:

```js
function onPromiseFulfilled() { codeCallback(); }
```

To: 

```js
function onPromiseFulfilled(value) { codeCallback(); return value; }
```

FYI, by referencing the original `_promise` - you're catching the same side effect that I demonstrated in my jsbin - you're calling `.then()` on the _original promise_, and therefore getting the _original value_ (because, as you say, promises are immutable!)

---

I'm going to close this issue - because I am pretty sure this is the problem you mention. If its not though, let me know and I'll re-open it right away and we can have another look at it. Enjoy the rest of your day and make sure you don't overwork yourself!

**Comment by SamPlacette** [comment]
I'm now using promisify-supertest (https://www.npmjs.com/package/promisify-supertest) instead of chai-http and my tests just work. This issue is no longer blocking me but I believe it will affect other people who choose to use chai-http.

**Comment by keithamus** [comment]
Good to hear your problem is fixed. I'll still welcome a reduced test case if you have the time at any point. Also, I'd be interested to know if your test code has changed with `promisify-supertest`.

**Comment by keithamus** [comment]
FYI it looks like if you dropped in that package to your existing code, the reason it would work is because the `request` object doesn't implement a `then` in its api (instead, a promise is returned from the `end()`) callback. While this looks like it'd be fine in the test case you provided, you should know that the HTTP request won't finish by the time the `this.When` ends (unless you call `end()` within the `this.When`) and instead will finish in `this.Then`.

**Comment by WORMSS** [comment]
I cannot say for sure what chai is meant to be doing but,
```javascript
  this._promise = this._promise.then(onResolve, onReject);
  return this;
```
This is not how normal promises should work internally.
You would want just
````diff
-   this._promise = this._promise.then(onResolve, onReject);
-   return this;
+   return this._promise.then(onResolve, onReject);
````
