### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by BigstickCarpet** [chaijs/chai-http#68]
Chai and Superagent can both be run in Node or in web browsers.  It would be great if your plugin worked in browsers too.  This would allow people to write _universal_ tests that can run in Node (great for CI) and in browsers (great for real-world testing).  Mocha also supports both Node and web browsers, so it's dead-simple to accomplish truly universal tests.

I don't think it would even require many changes to the code, since most of your dependencies are already universal.  And some dependencies (like cookie jar) wouldn't be needed when running in a browser.  You could probably just bundle your existing code via Browserify or WebPack.

**Comment by keithamus** [comment]
Thanks for the issue @BigstickCarpet.

You're quite right - it could be useful to have this work in the browser. Do you fancy trying to tackle this? If you need any help let me know.

**Comment by BigstickCarpet** [comment]
Sure, I can take a crack at it.  Does my approach sound good to you? I'll just add Browserify to package it up into a browser-safe bundle.

**Comment by keithamus** [comment]
Sounds perfect :smile:.

**Comment by BigstickCarpet** [comment]
**Step 1:** getting all the existing tests passing.   I've submitted a PR for that: https://github.com/chaijs/chai-http/pull/69

**Comment by BigstickCarpet** [comment]
*Step 2:* browser support.  Done.  :)

**Comment by keithamus** [comment]
@BigstickCarpet this one can be closed right? I'm going to close it for now, LMK if it needs re-opening 😄

**Comment by BigstickCarpet** [comment]
Yep.  sorry, I should have closed it months ago
