### ISSUE TITLE
header regex not working

### ISSUE THREAD

**Issue by reesew** [chaijs/chai-http#76]
I'm having trouble with the regex functionality of the header expectations. It seems to fail no matter what.

`expect(res).to.have.header('content-type', /json/);`
and even
`expect(res).to.have.header('content-type', /.*/);`

`Uncaught AssertionError: expected header 'content-type' to have value /.*/ but got 'application/api-problem+json; charset=utf-8'`

Am I missing something?

**Comment by keithamus** [comment]
@reesew sorry it has taken so long to get back to you on this. Are you still experiencing this issue? I've been using this today and it is "working fine for me"™ but I'd like to make sure its working well for you. Do you have a complete code example of this failing?

**Comment by reesew** [comment]
i don't. i originally had this problem before updating superagent manually, but it appears to have been fixed in the latest version, maybe because of PR #99
