### ISSUE TITLE
Add `done` to documentation

### ISSUE THREAD

**Issue by sambostock** [chaijs/chai-http#79]
# TL;DR:

Documentation doesn't mention the **required** use of `done`:

```javascript
// Fails, as expected.
it('should fail', function(done) {   // <= done parameter not mentioned in docs
  chai.request('https://github.com')
  .get('/')
  .end(function(err, res) {
    res.should.have.status(123) ;    // <= fails, as expected
    done() ;                         // <= done call not mentioned in docs
  }) ;
}) ;

// Silently passes!
it('silently passes', function() {   // <= missing done parameter
  chai.request('https://github.com')
  .get('/')
  .end(function(err, res) {
    res.should.have.status(123) ;    // <= passes silently (never fails)
                                     // <= missing call to done()
  }) ;
}) ;
```

----

## Details

**Nowhere in the documentation or examples do you mention the use of `done` when writing tests.**  In retrospect, it is obvious that it should be called in asynchronous test, but as a new user, not knowing this (and not seeing it in the documentation) was a huge pain.  Tests using `chai-http` without `done` pass silently, which was difficult to debug not knowing where to look.  The documentation should mention `done` at least once, and why it is required.

**Comment by keithamus** [comment]
Thanks for the issue @sambostock. Do you want to make a pull request for the docs for this?
