### ISSUE TITLE
does the request store the cookie?

### ISSUE THREAD

**Issue by stellanhaglund** [chaijs/chai-http#98]
Hi, I'm just wondering if the cookie is stored in some way if the header is set-cookie.

I'm writing some tests and after the login I want to do the rest on websockets where I would like to get the cookie on the upgradeReq, but I can't seem to find it.

**Comment by keithamus** [comment]
Hey @stellanhaglund thanks for the issue.

You need to use the Agent feature which will act like a single user revisiting the site, storing and sending back cookies. There is a [section about it in the readme](https://github.com/chaijs/chai-http#retaining-cookies-with-each-request). To quote:

> Sometimes you need to keep cookies from one request, and send them with the next. For this, .request.agent() is available:

> ```js
// Log in
var agent = chai.request.agent(app)
agent
  .post('/session')
  .send({ username: 'me', password: '123' })
  .then(function (res) {
    expect(res).to.have.cookie('sessionid');
    // The `agent` now has the sessionid cookie saved, and will send it
    // back to the server in the next request:
    return agent.get('/user/me')
      .then(function (res) {
         expect(res).to.have.status(200);
      })
  })
```

**Comment by keithamus** [comment]
I'll close this for now. Hopefully the above answers your question. If not let me know and we can discuss it further.

**Comment by pingzh** [comment]
@keithamus Thanks for your info. But do you know a way to test the cookie value and its expiration date? thanks.

**Comment by snapfractalpop** [comment]
@keithamus is it possible to use the agent, but on a new instance of the server? I want to write a test to assert that the session id is recognized after a server restart. If we can't reset the server object on the agent, maybe there is a way to set the cookie directly on the second request?
